"""Tier-2: per-group timeseries HTML report pages.

A timeseries in this codebase is a named group of repeat casts at one location
(yoyo CTDs, e.g. 24 h of repeated profiles).  Config is analogous to sections:
a name, a description, and a list of cast numbers.

The cruise-wide stacked overview plots (all casts, station-number x-axis) live on
index.html, generated by _index.py.  They are not timeseries pages.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import xarray as xr
from jinja2 import Environment

from ctdcast._version import __version__ as _VERSION
from ctdcast.analysis.teos10 import add_aou, add_teos10_profiles
from ctdcast.identity import compact_cast_list
from ctdcast.plots import (
    _MAX_SECTION_H,
    _W_FULL,
    _W_HALF,
    _W_THIRD,
    Panel,
    _make_ladcp_section_b64,
    _make_section_map_b64,
    _make_timeseries_b64,
    _make_ts_diagram_timeseries_b64,
)
from ctdcast.reports import _chrome as _tmpl
from ctdcast.reports._css import _JS_TOP_LINKS, SHARED_CSS
from ctdcast.reports._format import _fmt_utc
from ctdcast.reports._section import _expand_cast_numbers

# ---------------------------------------------------------------------------
# Variables to plot (in order)
# ---------------------------------------------------------------------------

_TIMESERIES_PHYSICS_VARS: list[tuple[str, str, str]] = [
    ("CT", "Conservative Temperature (°C)", "CT"),
    ("SA", "Absolute Salinity (g kg⁻¹)", "SA"),
    ("sigma0", "Potential density σ₀ (kg m⁻³)", "σ₀"),
]

_TIMESERIES_BIOGEO_VARS: list[tuple[str, str, str]] = [
    ("oxygen_1", "O₂ saturation (%)", "O₂"),
    ("fluorescence", "Fluorescence (mg m⁻³)", "Fluor"),
    ("turbidity", "Turbidity (NTU)", "Turb"),
]

# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

_TIMESERIES_TEMPLATE = (
    """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ ts_name }} — {{ cruise }}</title>
<style>
"""
    + SHARED_CSS
    + """\
/* Timeseries page */
.topbar {
  display: flex; align-items: center; justify-content: space-between;
  margin-bottom: 1.25rem; font-size: 0.85rem;
}
.breadcrumb a { color: var(--ocean); text-decoration: none; }
.breadcrumb a:hover { text-decoration: underline; }
.breadcrumb .sep { color: var(--muted); margin: 0 0.25rem; }
.cast-pill {
  display: inline-block; background: #4a6fa5; color: #fff;
  padding: 0.2rem 0.6rem; border-radius: 999px;
  font-size: 0.78rem; text-decoration: none; margin: 0.1rem 0.05rem;
}
.cast-pill:hover { opacity: 0.85; }
</style>
</head>
<body>
<div id="top"></div>

<div class="topbar">
  <nav class="breadcrumb">
    <a href="../index.html">Index</a>
    <span class="sep">›</span>
    <a href="../timeseries.html">Timeseries</a>
    <span class="sep">›</span>
    <span>{{ ts_name }}</span>
  </nav>
  <div class="nav-btns">
    {% if prev_name %}<a class="btn-nav" href="timeseries_{{ prev_name }}.html">← {{ prev_name }}</a>{% endif %}
    {% if next_name %}<a class="btn-nav" href="timeseries_{{ next_name }}.html">{{ next_name }} →</a>{% endif %}
  </div>
</div>

<div class="masthead" style="background:#27ae60;">
  <div class="masthead-header">
    <h1>{{ ts_name }}</h1>
    <span class="masthead-type">Timeseries</span>
  </div>
  <p class="sub" style="margin:0 0 0.6rem; text-align:right;">generated {{ generated_at }}</p>
  <div style="margin-top:0.65rem;margin-bottom:0.5rem">
    <span style="font-size:0.72rem;opacity:0.75;margin-right:0.3rem;">Pages:</span>
    <a href="../index.html" style="display:inline-block;padding:0.2em 0.65em;border-radius:4px;font-size:0.78rem;font-weight:700;text-decoration:none;color:#fff;margin:0 0.2rem 0.25rem 0;background:#2980b9">Summary</a>
    <a href="../station_index.html" style="display:inline-block;padding:0.2em 0.65em;border-radius:4px;font-size:0.78rem;font-weight:700;text-decoration:none;color:#fff;margin:0 0.2rem 0.25rem 0;background:#1a3a5c">Stations</a>
    <a href="../sections.html" style="display:inline-block;padding:0.2em 0.65em;border-radius:4px;font-size:0.78rem;font-weight:700;text-decoration:none;color:#fff;margin:0 0.2rem 0.25rem 0;background:#8e44ad">Sections</a>
    <a href="../timeseries.html" style="display:inline-block;padding:0.2em 0.65em;border-radius:4px;font-size:0.78rem;font-weight:700;text-decoration:none;color:#fff;margin:0 0.2rem 0.25rem 0;background:#27ae60;opacity:0.55">Timeseries</a>
    <a href="../leaflet.html" style="display:inline-block;padding:0.2em 0.65em;border-radius:4px;font-size:0.78rem;font-weight:700;text-decoration:none;color:#fff;margin:0 0.2rem 0.25rem 0;background:#EE3377">Interactive</a>
  </div>
  <dl class="meta-grid">
    <div><dt>Cruise</dt><dd>{{ cruise }}</dd></div>
    <div><dt>Ship</dt><dd>{{ ship }}</dd></div>
    <div><dt>CTD casts</dt><dd>{{ n_casts }}</dd></div>
    <div><dt>Start</dt><dd>{{ time_start_str }}</dd></div>
    <div><dt>End</dt><dd>{{ time_end_str }}</dd></div>
    <div><dt>Duration</dt><dd>{{ duration_str }}</dd></div>
  </dl>
</div>

<div class="jump-nav">
  {% if fig_location_b64 %}<a href="#s-map">Map</a>{% endif %}
  {% if physics_panels | selectattr("b64") | list %}<a href="#s-physics">Hydrography</a>{% endif %}
  {% if biogeo_panels | selectattr("b64") | list %}<a href="#s-biogeo">Biogeochemistry</a>{% endif %}
  {% for card in extra_cards %}<a href="#s-{{ card.id }}">{{ card.short }}</a>{% endfor %}
</div>

<div style="margin-bottom:1rem;">
  {% for cn in cast_nums %}
  <a class="cast-pill" href="../stations/cast_{{ cn }}.html">{{ cn }}</a>
  {% endfor %}
</div>

{% macro ts_panel_group(panels, slot, anchor, heading) %}
{% if panels | selectattr("b64") | list %}
{% if heading %}<h2 id="{{ anchor }}">{{ heading }}</h2>{% endif %}
{% if slot == "slot-third" %}
<div class="fig-row">
  {% for panel in panels %}{% if panel.b64 %}
  <figure class="{{ slot }}">
    <img src="data:image/png;base64,{{ panel.b64 }}" alt="{{ panel.title }}">
    <figcaption>{{ panel.title }}</figcaption>
  </figure>
  {% endif %}{% endfor %}
</div>
{% elif slot == "slot-half" %}
{% for row in panels | batch(2, None) %}
<div class="fig-row">
  {% for panel in row %}{% if panel and panel.b64 %}
  <figure class="{{ slot }}">
    <img src="data:image/png;base64,{{ panel.b64 }}" alt="{{ panel.title }}">
    <figcaption>{{ panel.title }}</figcaption>
  </figure>
  {% endif %}{% endfor %}
</div>
{% endfor %}
{% else %}
{% for panel in panels %}{% if panel.b64 %}
<div class="fig-row">
  <figure class="{{ slot }}">
    <img src="data:image/png;base64,{{ panel.b64 }}" alt="{{ panel.title }}">
    <figcaption>{{ panel.title }}</figcaption>
  </figure>
</div>
{% endif %}{% endfor %}
{% endif %}
{% endif %}
{% endmacro %}

{% if fig_location_b64 %}
<h2 id="s-map">Map</h2>
<div class="fig-row">
  <figure class="slot-third">
    <img src="data:image/png;base64,{{ fig_location_b64 }}" alt="Yoyo location map">
  </figure>
</div>
{% endif %}

{{ ts_panel_group(physics_panels, ts_slot, "s-physics", "Hydrography") }}
{{ ts_panel_group(biogeo_panels, ts_slot, "s-biogeo", "Biogeochemistry") }}

{% if not physics_panels and not biogeo_panels %}
<p style="color:#888">No data available for these casts.</p>
{% endif %}

{% for card in extra_cards %}
<h2 id="s-{{ card.id }}">{{ card.title }}</h2>
{% if card.id == "ts" %}
<div class="fig-row">
  {% for panel in card.panels %}{% if panel.b64 %}
  <figure class="slot-third">
    <img src="data:image/png;base64,{{ panel.b64 }}" alt="{{ panel.title }}">
    <figcaption>{{ panel.title }}</figcaption>
  </figure>
  {% endif %}{% endfor %}
</div>
{% else %}
{{ ts_panel_group(card.panels, ts_slot, "", "") }}
{% endif %}
{% endfor %}

"""
    + _tmpl.FOOTER_TAIL
    + _JS_TOP_LINKS
)


# ---------------------------------------------------------------------------
# Public function
# ---------------------------------------------------------------------------


def generate_timeseries_page(
    ts_name: str,
    ts_cfg: dict,
    profiles_path: Path,
    out_dir: Path,
    force: bool = False,
    section_style: str = "contourf",
    vmin_override: dict[str, float] | None = None,
    vmax_override: dict[str, float] | None = None,
    all_meta: list[dict] | None = None,
    ladcp_dir: Path | None = None,
    ladcp_pattern: str | None = None,
    dbar_step: int = 1,
    prev_name: str | None = None,
    next_name: str | None = None,
) -> Path | None:
    """Generate a per-timeseries HTML page for a named group of repeat casts.

    Plots both downcast and upcast profiles sorted by time_start on a shared
    time x-axis.  Output: ``<out_dir>/timeseries/timeseries_<ts_name>.html``.

    Parameters
    ----------
    ts_name:
        Group name (used in filename and page title).
    ts_cfg:
        Dict with ``cast_numbers``, ``description``, and ``color`` keys.
    profiles_path:
        Path to ``profiles.nc``.
    out_dir:
        Root output directory.
    force:
        Overwrite existing file if True.
    section_style:
        ``"pcolormesh"`` or ``"contourf"``.
    vmin_override, vmax_override:
        Per-variable colormap limit overrides.
    all_meta:
        List of per-cast metadata dicts (keys ``lat``, ``lon``, ``cast_num``);
        used to render a cruise-context location map.  If None, no map is shown.
    ladcp_dir:
        Directory containing processed LADCP ``.mat`` files.
        If None, the LADCP velocity panel is omitted.
    ladcp_pattern:
        Filename pattern for LADCP files, e.g. ``"msm_142_1_*.mat"``.
        The ``*`` is replaced with the zero-padded cast number.
        Falls back to ``NNN.mat`` if not given.
    dbar_step:
        Subsample the pressure axis by this step before plotting (default 1,
        no subsampling).  ``build_profiles()`` always stores 1-dbar data;
        this controls plot-time resolution only.
    prev_name:
        Name of the preceding timeseries group (for the ← nav button).  None omits the button.
    next_name:
        Name of the following timeseries group (for the → nav button).  None omits the button.

    Returns
    -------
    Path to the written HTML file, or None if skipped or failed.
    """
    out_file = out_dir / "timeseries" / f"timeseries_{ts_name}.html"
    if out_file.exists() and not force:
        return out_file
    out_file.parent.mkdir(parents=True, exist_ok=True)

    cast_nums = _expand_cast_numbers(ts_cfg.get("cast_numbers", []))
    if not cast_nums:
        return None

    if not profiles_path.exists():
        return None

    try:
        ds_all = xr.open_dataset(
            profiles_path, decode_timedelta=False, engine="netcdf4"
        ).load()
    except Exception:  # noqa: BLE001
        return None

    all_cast_nums = ds_all["cast_number"].values
    mask = np.isin(all_cast_nums, cast_nums)
    if not mask.any():
        ds_all.close()
        return None

    ds_ts = ds_all.isel(N_PROF=mask)
    if dbar_step > 1:
        p_idx = np.arange(0, ds_ts.sizes["pressure"], dbar_step)
        ds_ts = ds_ts.isel(pressure=p_idx)
    ds_ts = add_teos10_profiles(ds_ts)
    ds_ts = add_aou(ds_ts)

    # Sort all profiles (both down and up) by time_start
    order = np.argsort(ds_ts["time_start"].values)
    ds_ts = ds_ts.isel(N_PROF=order)

    cruise: str = ds_all.attrs.get("cruise", "odb2026")
    ship: str = ds_all.attrs.get(
        "ship",
        ds_all.attrs.get("platform", ds_all.attrs.get("vessel", "UNK")),
    )
    n_profiles = int(mask.sum())
    n_casts = len(cast_nums)

    times = ds_ts["time_start"].values
    time_start_str = _fmt_utc(times[0])
    time_end_str = _fmt_utc(times[-1])
    _dt_hours = (
        float((times[-1] - times[0]) / np.timedelta64(1, "h"))
        if len(times) > 1
        else 0.0
    )
    if _dt_hours >= 48.0:
        duration_str = f"{_dt_hours / 24:.1f} d ({_dt_hours:.0f} h)"
    else:
        duration_str = f"{_dt_hours:.1f} h"

    # Downcast profiles only — used for both the location map and LADCP.
    # Up/down share the same location; restricting to downcast avoids duplicate
    # scatter markers piling up at the same point.
    ds_down = (
        ds_ts.isel(N_PROF=ds_ts["cast_type"].values == "down")
        if "cast_type" in ds_ts
        else ds_ts
    )
    yoyo_lats = ds_down["latitude"].values if "latitude" in ds_down else np.array([])
    yoyo_lons = ds_down["longitude"].values if "longitude" in ds_down else np.array([])
    yoyo_cast_nums = [int(c) for c in ds_down["cast_number"].values]
    fig_location_b64: str | None = None
    if len(yoyo_lats) and np.any(np.isfinite(yoyo_lats)):
        # Compute cluster bounding radius in km, then set margin = 2× radius
        # (min 2 km) converted to degrees separately for lat and lon so the
        # rendered map is Mercator-square.
        _fin_lats = yoyo_lats[np.isfinite(yoyo_lats)]
        _fin_lons = yoyo_lons[np.isfinite(yoyo_lons)]
        _mean_lat = float(np.nanmedian(_fin_lats))
        _cos_lat = float(np.cos(np.deg2rad(_mean_lat)))
        _lat_km = float((_fin_lats.max() - _fin_lats.min()) * 111.0)
        _lon_km = float((_fin_lons.max() - _fin_lons.min()) * 111.0 * _cos_lat)
        _radius_km = max(_lat_km, _lon_km) / 2.0
        _context_km = max(_radius_km * 2.0, 2.0)
        _margin_lat = _context_km / 111.0
        _margin_lon = _context_km / (111.0 * max(_cos_lat, 0.05))
        fig_location_b64 = _make_section_map_b64(
            list(yoyo_lats),
            list(yoyo_lons),
            yoyo_cast_nums,
            min_margin=_margin_lat,
            min_margin_lon=_margin_lon,
        )

    vmin = vmin_override or {}
    vmax = vmax_override or {}

    # Slot and figure width based on cast count
    if n_casts >= 30:
        ts_slot = "slot-full"
        ts_figw = _W_FULL
    elif n_casts >= 15:
        ts_slot = "slot-half"
        ts_figw = _W_HALF
    else:
        ts_slot = "slot-third"
        ts_figw = _W_THIRD

    def _ts_panel(var: str, label: str, short: str) -> Panel:
        b64 = _make_timeseries_b64(
            ds_ts,
            var,
            label,
            style=section_style,
            vmin=vmin.get(var),
            vmax=vmax.get(var),
            figw=ts_figw,
        )
        return Panel(b64=b64, title=label, short=short)

    physics_panels = [_ts_panel(*t) for t in _TIMESERIES_PHYSICS_VARS]
    biogeo_panels = [_ts_panel(*t) for t in _TIMESERIES_BIOGEO_VARS]

    _ts_diagram_b64: str | None = _make_ts_diagram_timeseries_b64(ds_ts)

    # LADCP: use downcast profiles only, x-axis = hours since first cast
    _ladcp_ts_panels: list[Panel] = []
    if ladcp_dir is not None:
        ladcp_cast_nums = [int(c) for c in ds_down["cast_number"].values]
        ladcp_lats = ds_down["latitude"].values.tolist()
        ladcp_lons = ds_down["longitude"].values.tolist()
        t_ns = ds_down["time_start"].values.astype("datetime64[ns]").astype(float)
        t_hours = (t_ns - t_ns[0]) / 3.6e12 if len(t_ns) > 0 else np.zeros(0)
        _ladcp_ts_panels = [
            p
            for p in _make_ladcp_section_b64(
                ladcp_cast_nums,
                t_hours,
                "Hours since start",
                ladcp_dir,
                lats=ladcp_lats,
                lons=ladcp_lons,
                figsize=(ts_figw, _MAX_SECTION_H),
                ladcp_pattern=ladcp_pattern,
                style=section_style,
            )
            if p.b64
        ]

    _extra_raw: dict[str, dict | None] = {
        "ladcp": {
            "id": "ladcp",
            "title": "Velocity (U east, V north)",
            "short": "Velocity",
            "panels": _ladcp_ts_panels,
        }
        if _ladcp_ts_panels
        else None,
        "ts": {
            "id": "ts",
            "title": "T–S diagram (profiles coloured by time)",
            "short": "T–S diagram",
            "panels": [Panel(b64=_ts_diagram_b64, title="T–S diagram")],
        }
        if _ts_diagram_b64
        else None,
    }
    extra_cards = [_extra_raw[k] for k in _tmpl.EXTRA_CARD_ORDER if _extra_raw.get(k)]

    ctx: dict[str, Any] = {
        "ts_name": ts_name,
        "ts_description": ts_cfg.get("description", ""),
        "cruise": cruise,
        "ship": ship,
        "n_casts": n_casts,
        "n_profiles": n_profiles,
        "time_start_str": time_start_str,
        "time_end_str": time_end_str,
        "duration_str": duration_str,
        "cast_list_str": compact_cast_list(cast_nums),
        "cast_nums": [f"{n:03d}" for n in sorted(cast_nums)],
        "physics_panels": physics_panels,
        "biogeo_panels": biogeo_panels,
        "ts_slot": ts_slot,
        "fig_location_b64": fig_location_b64,
        "extra_cards": extra_cards,
        "prev_name": prev_name or "",
        "next_name": next_name or "",
        "version": _VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }

    env = Environment(autoescape=True)
    html = env.from_string(_TIMESERIES_TEMPLATE).render(**ctx)
    out_file.write_text(html, encoding="utf-8")
    ds_all.close()
    return out_file
