"""Tier-2: per-group timeseries HTML report pages.

A timeseries in this codebase is a named group of repeat casts at one location
(yoyo CTDs, e.g. 24 h of repeated profiles).  Config is analogous to sections:
a name, a description, and a list of cast numbers.

The cruise-wide stacked overview plots (all casts, station-number x-axis) live on
index.html, generated by _index.py.  They are not timeseries pages.
"""

from __future__ import annotations

import dataclasses
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

import numpy as np
import xarray as xr

from ctdcast._version import __version__ as _VERSION
from ctdcast.analysis.derive import derive_AOU as add_aou
from ctdcast.analysis.derive import derive_teos10_profiles as add_teos10_profiles
from ctdcast.config.parameters import (
    SECTION_BIOGEO_VARS,
    SECTION_PHYSICS_VARS,
    UNKNOWN_CRUISE_ID,
    resolve_sensor_var,
    vlabel,
)
from ctdcast.config.report_config import DEFAULT_REPORT_CONFIG, ReportConfig
from ctdcast.config.report_tokens import (
    ROLE_ACCENT,
    MAX_SECTION_H as _MAX_SECTION_H,
    W_FULL as _W_FULL,
    W_HALF as _W_HALF,
    W_THIRD as _W_THIRD,
)
from ctdcast.identity import compact_cast_list, expand_cast_ids, format_cast_id
from ctdcast.reports._manifest import (
    Panel,
    PanelGroup,
    Profile,
    ResolvedReport,
    Section,
    resolve,
)
from ctdcast.reports._report_css import _JS_TOP_LINKS, SHARED_CSS
from ctdcast.reports._env import get_template
from ctdcast.reports._format import _fmt_utc, profile_cast_suffixes
from ctdcast.reports._plots import (
    RenderedPanel,
    _make_ladcp_section_b64,
    _make_section_map_b64,
    _make_timeseries_b64,
    _make_ts_diagram_timeseries_b64,
)

# Panel variables are defined in ctdcast.config.parameters:
#   SECTION_PHYSICS_VARS / SECTION_BIOGEO_VARS  (shared with _index.py, _section.py)

# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Public function
# ---------------------------------------------------------------------------


def generate_timeseries_page(
    ts_name: str,
    ts_cfg: dict,
    profiles_path: Path,
    out_dir: Path,
    force: bool = False,
    section_style: str = "contourf",
    vmin_override: dict[str, float] | None = None,
    vmax_override: dict[str, float] | None = None,
    all_meta: list[dict] | None = None,  # noqa: ARG001
    ladcp_dir: Path | None = None,
    ladcp_pattern: str | None = None,
    dbar_step: int = 1,
    prev_name: str | None = None,
    next_name: str | None = None,
    cruise_info: dict[str, Any] | None = None,
    cfg: ReportConfig = DEFAULT_REPORT_CONFIG,
) -> Path | None:
    """Generate a per-timeseries HTML page for a named group of repeat casts.

    Plots both downcast and upcast profiles sorted by time_start on a shared
    time x-axis.  Output: ``<out_dir>/timeseries/timeseries_<ts_name>.html``.

    Parameters
    ----------
    ts_name:
        Group name (used in filename and page title).
    ts_cfg:
        Dict with ``cast_numbers``, ``description``, and ``color`` keys.
    profiles_path:
        Path to ``profiles.nc``.
    out_dir:
        Root output directory.
    force:
        Overwrite existing file if True.
    section_style:
        ``"pcolormesh"`` or ``"contourf"``.
    vmin_override, vmax_override:
        Per-variable colormap limit overrides.
    all_meta:
        List of per-cast metadata dicts (keys ``lat``, ``lon``, ``cast_num``);
        used to render a cruise-context location map.  If None, no map is shown.
    ladcp_dir:
        Directory containing processed LADCP ``.mat`` files.
        If None, the LADCP velocity panel is omitted.
    ladcp_pattern:
        Filename pattern for LADCP files, e.g. ``"msm_142_1_*.mat"``.
        The ``*`` is replaced with the zero-padded cast number.
        Falls back to ``NNN.mat`` if not given.
    dbar_step:
        Subsample the pressure axis by this step before plotting (default 1,
        no subsampling).  ``build_profiles()`` always stores 1-dbar data;
        this controls plot-time resolution only.
    prev_name:
        Name of the preceding timeseries group (for the ← nav button).  None omits the button.
    next_name:
        Name of the following timeseries group (for the → nav button).  None omits the button.

    Returns
    -------
    Path to the written HTML file, or None if skipped or failed.
    """
    out_file = out_dir / "timeseries" / f"timeseries_{ts_name}.html"
    if out_file.exists() and not force:
        return out_file
    out_file.parent.mkdir(parents=True, exist_ok=True)

    cast_ids = expand_cast_ids(ts_cfg.get("cast_numbers", []))
    if not cast_ids:
        return None
    cast_nums = [n for n, _s in cast_ids]

    if not profiles_path.exists():
        return None

    try:
        ds_all = xr.open_dataset(
            profiles_path, decode_timedelta=False, engine="netcdf4"
        ).load()
    except Exception:  # noqa: BLE001
        return None

    # Identity is the (cast_number, cast_suffix) pair, so a repeat "b" occupation
    # is selected as a distinct event from its plain sibling.
    all_cast_nums = ds_all["cast_number"].values
    all_suffix = profile_cast_suffixes(ds_all)
    wanted = set(cast_ids)
    mask = np.array(
        [(int(n), s) in wanted for n, s in zip(all_cast_nums, all_suffix, strict=True)]
    )
    if not mask.any():
        ds_all.close()
        return None

    ds_ts = ds_all.isel(N_PROF=mask)
    if dbar_step > 1:
        p_idx = np.arange(0, ds_ts.sizes["pressure"], dbar_step)
        ds_ts = ds_ts.isel(pressure=p_idx)
    ds_ts = add_teos10_profiles(ds_ts)
    ds_ts = add_aou(ds_ts)

    # Sort all profiles (both down and up) by time_start
    order = np.argsort(ds_ts["time_start"].values)
    ds_ts = ds_ts.isel(N_PROF=order)

    # Distinct suffixed cast ids ("010", "010b") in occupation order, for pills
    # that link each event to its own cast page.
    _ts_suffix = profile_cast_suffixes(ds_ts)
    cast_id_strs: list[str] = []
    for _n, _s in zip(ds_ts["cast_number"].values, _ts_suffix, strict=True):
        _key = format_cast_id(int(_n), _s)
        if _key not in cast_id_strs:
            cast_id_strs.append(_key)

    _ci = cruise_info or {}
    cruise: str = (
        _ci.get("cruise_id") or ds_all.attrs.get("cruise") or UNKNOWN_CRUISE_ID
    )
    ship: str = (
        _ci.get("ship")
        or ds_all.attrs.get("ship")
        or ds_all.attrs.get("platform")
        or ds_all.attrs.get("vessel")
        or "UNK"
    )
    n_profiles = int(mask.sum())
    n_casts = len(cast_nums)

    times = ds_ts["time_start"].values
    time_start_str = _fmt_utc(times[0])
    time_end_str = _fmt_utc(times[-1])
    _dt_hours = (
        float((times[-1] - times[0]) / np.timedelta64(1, "h"))
        if len(times) > 1
        else 0.0
    )
    if _dt_hours >= 48.0:
        duration_str = f"{_dt_hours / 24:.1f} d ({_dt_hours:.0f} h)"
    else:
        duration_str = f"{_dt_hours:.1f} h"

    # Downcast profiles only — used for both the location map and LADCP.
    # Up/down share the same location; restricting to downcast avoids duplicate
    # scatter markers piling up at the same point.
    ds_down = (
        ds_ts.isel(N_PROF=ds_ts["cast_type"].values == "down")
        if "cast_type" in ds_ts
        else ds_ts
    )
    yoyo_lats = ds_down["latitude"].values if "latitude" in ds_down else np.array([])
    yoyo_lons = ds_down["longitude"].values if "longitude" in ds_down else np.array([])
    yoyo_cast_nums = [int(c) for c in ds_down["cast_number"].values]
    fig_location_b64: str | None = None
    if len(yoyo_lats) and np.any(np.isfinite(yoyo_lats)):
        # Compute cluster bounding radius in km, then set margin = 2× radius
        # (min 2 km) converted to degrees separately for lat and lon so the
        # rendered map is Mercator-square.
        _fin_lats = yoyo_lats[np.isfinite(yoyo_lats)]
        _fin_lons = yoyo_lons[np.isfinite(yoyo_lons)]
        _mean_lat = float(np.nanmedian(_fin_lats))
        _cos_lat = float(np.cos(np.deg2rad(_mean_lat)))
        _lat_km = float((_fin_lats.max() - _fin_lats.min()) * 111.0)
        _lon_km = float((_fin_lons.max() - _fin_lons.min()) * 111.0 * _cos_lat)
        _radius_km = max(_lat_km, _lon_km) / 2.0
        _context_km = max(_radius_km * 2.0, 2.0)
        _margin_lat = _context_km / 111.0
        _margin_lon = _context_km / (111.0 * max(_cos_lat, 0.05))
        fig_location_b64 = _make_section_map_b64(
            list(yoyo_lats),
            list(yoyo_lons),
            yoyo_cast_nums,
            min_margin=_margin_lat,
            min_margin_lon=_margin_lon,
            cfg=cfg,
        )

    vmin = vmin_override or {}
    vmax = vmax_override or {}

    # Slot and figure width based on cast count
    if n_casts >= 30:
        ts_slot = "slot-full"
        ts_figw = _W_FULL
    elif n_casts >= 15:
        ts_slot = "slot-half"
        ts_figw = _W_HALF
    else:
        ts_slot = "slot-third"
        ts_figw = _W_THIRD

    # T–S diagram is a single auxiliary panel; a None means an empty plot, so it is
    # rendered here and fed to the T–S section only when present (silently omitted
    # otherwise, as before), rather than shown as an "unavailable" stub.
    _ts_diagram_b64: str | None = _make_ts_diagram_timeseries_b64(ds_ts, cfg=cfg)
    ts_panels = (
        (
            RenderedPanel(
                b64=_ts_diagram_b64,
                title="T–S diagram (profiles coloured by time)",
                short="T–S diagram",
            ),
        )
        if _ts_diagram_b64
        else ()
    )

    # LADCP: use downcast profiles only, x-axis = hours since first cast.
    ladcp_panels: tuple[RenderedPanel, ...] = ()
    if ladcp_dir is not None:
        ladcp_cast_nums = [int(c) for c in ds_down["cast_number"].values]
        ladcp_lats = ds_down["latitude"].values.tolist()
        ladcp_lons = ds_down["longitude"].values.tolist()
        t_ns = ds_down["time_start"].values.astype("datetime64[ns]").astype(float)
        t_hours = (t_ns - t_ns[0]) / 3.6e12 if len(t_ns) > 0 else np.zeros(0)
        ladcp_panels = tuple(
            p
            for p in _make_ladcp_section_b64(
                ladcp_cast_nums,
                t_hours,
                "Hours since start",
                ladcp_dir,
                lats=ladcp_lats,
                lons=ladcp_lons,
                figsize=(ts_figw, _MAX_SECTION_H),
                ladcp_pattern=ladcp_pattern,
                style=section_style,
                cfg=cfg,
            )
            if p.b64
        )

    page_ctx = TimeseriesPageCtx(
        ds_ts=ds_ts,
        section_style=section_style,
        vmin=vmin,
        vmax=vmax,
        ts_figw=ts_figw,
        ts_slot_key=ts_slot.removeprefix("slot-"),
        fig_location_b64=fig_location_b64,
        ts_panels=ts_panels,
        ladcp_panels=ladcp_panels,
        cfg=cfg,
    )
    report = resolve_timeseries(page_ctx)

    ctx: dict[str, Any] = {
        "ts_name": ts_name,
        "ts_description": ts_cfg.get("description", ""),
        "cruise": cruise,
        "ship": ship,
        "n_casts": n_casts,
        "n_profiles": n_profiles,
        "time_start_str": time_start_str,
        "time_end_str": time_end_str,
        "duration_str": duration_str,
        "cast_list_str": compact_cast_list(cast_nums),
        "cast_nums": cast_id_strs,
        "report": report,
        "prev_name": prev_name or "",
        "next_name": next_name or "",
        "version": _VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }

    html = get_template("timeseries_page.html").render(
        **ctx,
        css=SHARED_CSS,
        js_top_links=_JS_TOP_LINKS,
        nav_prefix="../",
        nav_current="timeseries",
        masthead_bg=ROLE_ACCENT["aggregate-b"],
    )
    out_file.write_text(html, encoding="utf-8")
    ds_all.close()
    return out_file


# ---------------------------------------------------------------------------
# Timeseries manifest — the timeseries page as data (mirrors _section.py)
# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class TimeseriesPageCtx:
    """Per-timeseries render context: the frozen inputs every panel reads.

    Holds the values derived once per group (the selected profiles, colour limits,
    the cast-count-driven figure width and slot, and the pre-rendered location map,
    LADCP and T–S panels) so a panel's ``render`` depends only on this object.
    """

    ds_ts: Any
    section_style: str
    vmin: dict[str, float]
    vmax: dict[str, float]
    ts_figw: float
    ts_slot_key: str
    fig_location_b64: str | None
    ts_panels: tuple[RenderedPanel, ...]
    ladcp_panels: tuple[RenderedPanel, ...]
    cfg: ReportConfig


def _ts_slot(c: TimeseriesPageCtx) -> str:
    """Return the cast-count-driven CSS slot key shared by every field panel."""
    return c.ts_slot_key


def _ts_field_render(
    var: str, *, canonical: str | None, optional: bool
) -> Callable[[TimeseriesPageCtx], str | None]:
    """Build the render closure for one timeseries field (var vs cast time)."""

    def _render(c: TimeseriesPageCtx) -> str | None:
        resolved = resolve_sensor_var(c.ds_ts, var) if optional else var
        key = canonical or var
        _vmin = (
            c.vmin.get(resolved)
            if c.vmin.get(resolved) is not None
            else c.vmin.get(key)
        )
        _vmax = (
            c.vmax.get(resolved)
            if c.vmax.get(resolved) is not None
            else c.vmax.get(key)
        )
        return _make_timeseries_b64(
            c.ds_ts,
            resolved,
            vlabel(var),
            style=c.section_style,
            vmin=_vmin,
            vmax=_vmax,
            figw=c.ts_figw,
            optional=optional,
            cfg=c.cfg,
        )

    return _render


def _ts_field_panel(
    var: str, *, canonical: str | None = None, optional: bool = False
) -> Panel:
    """Build a timeseries field :class:`Panel` for *var* at the cast-count slot."""
    return Panel(
        id=f"timeseries_{canonical or var}",
        slot=_ts_slot,
        render=_ts_field_render(var, canonical=canonical, optional=optional),
    )


def _ts_ladcp_panel(rp: RenderedPanel) -> Panel:
    """Wrap a pre-rendered LADCP U/V panel as a timeseries :class:`Panel`."""
    return Panel(
        id=f"velocity_{rp.short}",
        slot=_ts_slot,
        render=lambda _c, _b64=rp.b64: _b64,
    )


def _ts_diagram_panel(rp: RenderedPanel) -> Panel:
    """Wrap the pre-rendered T–S diagram as a third-width :class:`Panel`."""
    return Panel(
        id="ts_diagram_panel",
        slot="third",
        render=lambda _c, _b64=rp.b64: _b64,
    )


def _ts_biogeo_present(c: TimeseriesPageCtx) -> list[str]:
    """Return the biogeo vars present on this timeseries, in canonical order."""
    return [v for v in SECTION_BIOGEO_VARS if resolve_sensor_var(c.ds_ts, v) in c.ds_ts]


#: Only the location map is fixed; fields, LADCP and T–S are data-driven groups.
TIMESERIES_PANELS: dict[str, Panel] = {
    "ts_location_map": Panel(
        id="ts_location_map",
        slot="third",
        applies_to=lambda c: c.fig_location_b64 is not None,
        render=lambda c: c.fig_location_b64,
    ),
}


#: The timeseries page profile — the same shape and section ids as the section
#: page (so the shared anchors and the legacy #s-* aliases resolve identically),
#: but with time-axis panels and cast-count-driven widths.
TIMESERIES_DEFAULT: Profile = Profile(
    numbering="flat",
    entries=(
        Section(
            "map",
            "Map",
            ("ts_location_map",),
            intro="Location of the repeat CTD casts in this group.",
        ),
        Section(
            "hydrography",
            "Hydrography",
            (
                PanelGroup(
                    over=lambda _c: list(SECTION_PHYSICS_VARS), panel=_ts_field_panel
                ),
            ),
            intro=(
                "Time series of conservative temperature (CT), absolute salinity "
                "(SA) and potential density (σ₀) against cast time. The σ₀ panel "
                "carries the 27.7 and 27.8 kg m⁻³ isopycnals (black, labelled). "
                "Triangles along the top mark each profile — downward for downcasts, "
                "upward for upcasts — with station numbers labelled at intervals "
                "above the downcasts."
            ),
        ),
        Section(
            "biogeochemistry",
            "Biogeochemistry",
            (
                PanelGroup(
                    over=_ts_biogeo_present,
                    panel=lambda v: _ts_field_panel(v, canonical=v, optional=True),
                ),
            ),
            intro=(
                "Time series of the biogeochemical sensors present in this group — "
                "oxygen, fluorescence and turbidity where available — against cast "
                "time."
            ),
        ),
        Section(
            "velocity",
            "Velocity (U east, V north)",
            (PanelGroup(over=lambda c: c.ladcp_panels, panel=_ts_ladcp_panel),),
            intro=(
                "Eastward (U) and northward (V) velocity from the LADCP, against "
                "hours since the first cast."
            ),
        ),
        Section(
            "ts_diagram",
            "T–S diagram",
            (PanelGroup(over=lambda c: c.ts_panels, panel=_ts_diagram_panel),),
            intro=(
                "Water-mass structure over the occupation in temperature–salinity "
                "space, profiles coloured by time."
            ),
        ),
    ),
)


def resolve_timeseries(ctx: TimeseriesPageCtx) -> ResolvedReport:
    """Resolve the timeseries profile against *ctx* into numbered, rendered sections."""
    return resolve(TIMESERIES_DEFAULT, ctx, TIMESERIES_PANELS)
