"""Shared Jinja2 HTML fragment constants.

Edit FOOTER_LINE once to change the footer across all generated pages.

Canonical extra-card order
--------------------------
Section and timeseries pages render ``extra_cards`` after the variable panels.
Both page modules must build ``extra_cards`` by filtering this tuple in order::

    extra_cards = [
        _build_card(k, ...)
        for k in EXTRA_CARD_ORDER
        if _build_card(k, ...) is not None
    ]

Adding a new card type: append its key here; insert the build logic in both
``section.py`` and ``timeseries.py`` (or return ``None`` if not applicable).
"""

from __future__ import annotations

#: Canonical rendering order for extra cards (after variable panels) on section
#: and timeseries pages.  Keys match the ``"id"`` field of each card dict.
EXTRA_CARD_ORDER: tuple[str, ...] = ("ladcp", "ts")

FOOTER_LINE = (
    "<footer>Generated by "
    '<a href="http://github.com/eleanorfrajka/ctdreport">ctdreport</a>'
    " v{{ version }} &nbsp;·&nbsp; {{ cruise }} &nbsp;·&nbsp; {{ generated_at }}"
    "</footer>"
)

#: Convenience tail for templates that end immediately after the footer.
FOOTER_TAIL = FOOTER_LINE + "\n</body>\n</html>"
