"""Tier-3: entry point — generates index, stations list, and sections list pages."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import numpy as np
import xarray as xr
import yaml
from jinja2 import Environment

from ctd_report._version import __version__ as _VERSION

from ctd_report._plots import (
    GEBCO_PATH,
    _make_all_sections_map_b64,
    _make_cruise_map_b64,  # noqa: F401 — kept for backward compat
    _make_overview_panel_b64,
    _make_section_ts_histogram_b64,
    _make_station_map_b64,  # noqa: F401 — kept for backward compat
)
from ctd_report._analysis import (
    _add_aou,
    _add_teos10_profiles,
    _compact_cast_list,
    _interpolate_bathy_at_casts,
)
from ctd_report._section import _expand_cast_numbers, generate_section_page
from ctd_report._station import generate_station_page

# ---------------------------------------------------------------------------
# HTML templates
# ---------------------------------------------------------------------------

_INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CTD Report — {{ cruise }}</title>
<style>
  :root { --ocean: #1a3a5c; --seafoam: #e8f4f8; --accent: #2e86ab; --text: #1a1a2e; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #f5f7fa; color: var(--text); }
  header { background: var(--ocean); color: #fff; padding: 1.25rem 1.5rem; }
  header h1 { font-size: 1.5rem; }
  header .meta { font-size: 0.9rem; opacity: 0.8; margin-top: 0.3rem; }
  .card {
    background: #fff; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    padding: 1.25rem; margin: 1rem 1.5rem;
  }
  .card h2 { font-size: 1.05rem; color: var(--ocean); margin-bottom: 0.75rem; }
  .hero { display: flex; gap: 1.5rem; align-items: flex-start; flex-wrap: wrap; }
  .hero img { max-height: 360px; width: auto; border-radius: 6px; }
  .hero-stats { display: grid; grid-template-columns: 1fr 1fr; gap: 0.75rem; min-width: 200px; }
  .stat { background: var(--seafoam); border-radius: 6px; padding: 0.75rem; text-align: center; }
  .stat .n { font-size: 2rem; font-weight: 700; color: var(--ocean); }
  .stat .lbl { font-size: 0.8rem; color: #555; }
  .btn {
    display: inline-block; background: var(--ocean); color: #fff;
    padding: 0.4rem 1.1rem; border-radius: 999px; text-decoration: none;
    font-size: 0.9rem; margin: 0.3rem;
  }
  .btn:hover { background: var(--accent); }
  .btn-sec { background: #2c6e49; }
  .btn-ts  { background: #7b2d8b; }
  .plot-wide { margin-top: 0.75rem; }
  .plot-wide img { max-width: 100%; height: auto; border-radius: 4px; }
  footer { text-align: center; padding: 1rem; font-size: 0.75rem; color: #999; }
</style>
</head>
<body>

<header>
  <h1>CTD Report — {{ cruise }}</h1>
  <div class="meta">
    {% if ship or cruise_id or project %}{{ ship }}{% if cruise_id %} · {{ cruise_id }}{% endif %}{% if project %} · {{ project }}{% endif %} &nbsp;|&nbsp; {% endif %}{{ date_range }} &nbsp;·&nbsp; {{ n_casts }} casts &nbsp;·&nbsp; {{ n_sections }} sections
  </div>
</header>

<div class="card">
  <div class="hero">
    {% if fig_map_b64 %}
    <img src="data:image/png;base64,{{ fig_map_b64 }}" alt="Station map">
    {% endif %}
    <div>
      <div class="hero-stats">
        <div class="stat"><div class="n">{{ n_casts }}</div><div class="lbl">CTD casts</div></div>
        <div class="stat"><div class="n">{{ n_sections }}</div><div class="lbl">Sections</div></div>
        <div class="stat"><div class="n">{{ max_depth_str }}</div><div class="lbl">Max depth</div></div>
        <div class="stat"><div class="n">{{ n_days }}</div><div class="lbl">Days at sea</div></div>
      </div>
      <div style="margin-top:1rem;">
        <a class="btn" href="station_index.html">All stations</a>
        <a class="btn btn-sec" href="sections.html">Sections</a>
        <a class="btn btn-ts" href="timeseries.html">Time series</a>
      </div>
    </div>
  </div>
</div>

{% for panel in overview_panels %}
{% if panel.b64 %}
<div class="card">
  <h2>{{ panel.title }}</h2>
  <div class="plot-wide">
    <img src="data:image/png;base64,{{ panel.b64 }}" alt="{{ panel.title }}">
  </div>
</div>
{% endif %}
{% endfor %}

{% if ts_b64 %}
<div class="card">
  <h2>T–S diagram (all downcast profiles)</h2>
  <div style="display:flex;justify-content:center;">
    <img src="data:image/png;base64,{{ ts_b64 }}" alt="Cruise T-S diagram"
         style="max-height:420px;width:auto;border-radius:4px;">
  </div>
</div>
{% endif %}

<footer>Generated by ctd_report v{{ version }} &nbsp;·&nbsp; {{ cruise }} &nbsp;·&nbsp; {{ generated_at }}</footer>
</body>
</html>"""


_STATIONS_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Station index — {{ cruise }}</title>
<style>
  :root { --ocean: #1a3a5c; --seafoam: #e8f4f8; --accent: #2e86ab; --text: #1a1a2e; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #f5f7fa; color: var(--text); }
  header { background: var(--ocean); color: #fff; padding: 1rem 1.5rem; }
  header h1 { font-size: 1.3rem; }
  nav { background: var(--seafoam); padding: 0.6rem 1.5rem; border-bottom: 1px solid #cdd8e3; }
  nav a { color: var(--ocean); text-decoration: none; font-size: 0.9rem; margin-right: 0.5rem; }
  nav a:hover { text-decoration: underline; }
  nav span { color: #888; font-size: 0.9rem; margin-right: 0.5rem; }
  .map-card {
    background: #fff; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    padding: 1.25rem; margin: 1rem 1.5rem; text-align: center;
  }
  .map-card img { max-width: 100%; max-height: 400px; width: auto; border-radius: 4px; }
  .card {
    background: #fff; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    padding: 1.25rem; margin: 1rem 1.5rem; overflow-x: auto;
  }
  table { width: 100%; border-collapse: collapse; font-size: 0.88rem; white-space: nowrap; }
  th {
    background: var(--ocean); color: #fff; padding: 0.5rem 0.75rem;
    text-align: left; position: sticky; top: 0; z-index: 1;
  }
  td { padding: 0.42rem 0.75rem; border-bottom: 1px solid #eee; vertical-align: middle; }
  tbody tr { cursor: pointer; }
  tbody tr:hover td { background: var(--seafoam); }
  .cast-link { color: var(--ocean); font-weight: 600; text-decoration: none; }
  .cast-link:hover { text-decoration: underline; }
  .filename { font-family: monospace; font-size: 0.82rem; color: #444; }
  .depth-pill {
    display: inline-block; padding: 0.18rem 0.55rem; border-radius: 999px;
    font-size: 0.78rem; font-weight: 600; white-space: nowrap;
  }
  .pill-btn {
    display: inline-block; padding: 0.18rem 0.55rem; border-radius: 999px;
    font-size: 0.75rem; text-decoration: none; white-space: nowrap; margin: 0.1rem 0.05rem;
  }
  .pill-profile { background: #1a3a5c; color: #fff; }
  .pill-section { background: #2c6e49; color: #fff; }
  .pill-btn:hover { opacity: 0.85; }
  .ladcp-yes { display:inline-block; padding:0.18rem 0.5rem; border-radius:999px; font-size:0.75rem; font-weight:600; background:#2c6e49; color:#fff; }
  .ladcp-no  { display:inline-block; padding:0.18rem 0.5rem; border-radius:999px; font-size:0.75rem; font-weight:600; background:#c0392b; color:#fff; }
  footer { text-align: center; padding: 1rem; font-size: 0.75rem; color: #999; }
</style>
</head>
<body>

<header><h1>Station index — {{ cruise }} ({{ stations|length }} casts)</h1></header>

<nav>
  <a href="index.html">Index</a> <span>›</span>
  <span>Stations</span>
</nav>

{% if cruise_map_b64 %}
<div class="map-card">
  <img src="data:image/png;base64,{{ cruise_map_b64 }}" alt="All cast positions">
</div>
{% endif %}

<div class="card">
  <table>
    <thead>
      <tr>
        <th>Cast</th>
        <th>File</th>
        <th>Start (UTC)</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Depth</th>
        {% if ladcp_configured %}<th>LADCP</th>{% endif %}
        <th>Links</th>
      </tr>
    </thead>
    <tbody>
    {% for s in stations %}
      <tr onclick="window.location='stations/cast_{{ s.cast_num }}.html'">
        <td><a class="cast-link" href="stations/cast_{{ s.cast_num }}.html">{{ s.cast_num }}</a></td>
        <td class="filename">{{ s.filename }}</td>
        <td>{{ s.time_start_str }}</td>
        <td>{{ s.lat_str }}</td>
        <td>{{ s.lon_str }}</td>
        <td><span class="depth-pill" style="background:{{ s.depth_bg }};color:{{ s.depth_fg }};">{{ s.max_depth_str }} dbar</span></td>
        {% if ladcp_configured %}
        <td>{% if s.ladcp_has %}<span class="ladcp-yes">✓</span>{% else %}<span class="ladcp-no">–</span>{% endif %}</td>
        {% endif %}
        <td>
          <a class="pill-btn pill-profile" href="stations/cast_{{ s.cast_num }}.html">Profile</a>
          {% for sec in s.sections %}
          <a class="pill-btn" style="background:{{ sec.color }};color:#fff;" href="sections/section_{{ sec.name }}.html">{{ sec.name }}</a>
          {% endfor %}
          {% for ts in s.timeseries %}
          <a class="pill-btn" style="background:{{ ts.color }};color:#fff;" href="timeseries/timeseries_{{ ts.name }}.html">{{ ts.name }}</a>
          {% endfor %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

<footer>Generated by ctd_report v{{ version }} &nbsp;·&nbsp; {{ cruise }} &nbsp;·&nbsp; {{ generated_at }}</footer>
</body>
</html>"""


_SECTIONS_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sections — {{ cruise }}</title>
<style>
  :root { --ocean: #1a3a5c; --seafoam: #e8f4f8; --accent: #2e86ab; --text: #1a1a2e; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #f5f7fa; color: var(--text); }
  header { background: var(--ocean); color: #fff; padding: 1rem 1.5rem; }
  header h1 { font-size: 1.3rem; }
  nav { background: var(--seafoam); padding: 0.6rem 1.5rem; border-bottom: 1px solid #cdd8e3; }
  nav a { color: var(--ocean); text-decoration: none; font-size: 0.9rem; margin-right: 0.5rem; }
  nav a:hover { text-decoration: underline; }
  nav span { color: #888; font-size: 0.9rem; margin-right: 0.5rem; }
  .content-row {
    display: flex; gap: 1.5rem; margin: 1rem 1.5rem; align-items: flex-start;
  }
  .map-sidebar { flex: 0 0 auto; max-width: 400px; }
  .map-sidebar img { width: 100%; height: auto; border-radius: 4px; }
  .grid {
    flex: 1;
    display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
    gap: 1rem;
  }
  .sec-card {
    background: #fff; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    padding: 1.1rem; border-left: 4px solid #1a3a5c;
  }
  .sec-card h3 { font-size: 1rem; color: var(--ocean); margin-bottom: 0.3rem; }
  .sec-card .desc { font-size: 0.85rem; color: #555; margin-bottom: 0.6rem; }
  .sec-card .info { font-size: 0.82rem; color: #777; }
  .btn {
    display: inline-block; background: var(--ocean); color: #fff;
    padding: 0.3rem 0.85rem; border-radius: 999px; text-decoration: none;
    font-size: 0.82rem; margin-top: 0.6rem;
  }
  .btn:hover { background: var(--accent); }
  .ladcp-yes { display:inline-block; padding:0.18rem 0.5rem; border-radius:999px; font-size:0.75rem; font-weight:600; background:#2c6e49; color:#fff; }
  .ladcp-no  { display:inline-block; padding:0.18rem 0.5rem; border-radius:999px; font-size:0.75rem; font-weight:600; background:#c0392b; color:#fff; }
  footer { text-align: center; padding: 1rem; font-size: 0.75rem; color: #999; }
</style>
</head>
<body>

<header><h1>Sections — {{ cruise }}</h1></header>

<nav>
  <a href="index.html">Index</a> <span>›</span>
  <span>Sections</span>
</nav>

<div class="content-row">
  {% if sections_map_b64 %}
  <div class="map-sidebar">
    <img src="data:image/png;base64,{{ sections_map_b64 }}" alt="Sections overview map">
  </div>
  {% endif %}
  <div class="grid">
  {% for sec in sections %}
  <div class="sec-card" style="border-left-color: {{ sec.color }}">
    <h3>{{ sec.name }}</h3>
    <div class="desc">{{ sec.description }}</div>
    <div class="info">{{ sec.n_casts }} casts &nbsp;·&nbsp; casts {{ sec.cast_range }}</div>
    {% if ladcp_configured %}
    <div style="margin-top:0.4rem;">
      {% if sec.ladcp_has %}<span class="ladcp-yes">✓ LADCP</span>{% else %}<span class="ladcp-no">– LADCP</span>{% endif %}
    </div>
    {% endif %}
    {% if sec.report_exists %}
    <a class="btn" href="sections/section_{{ sec.name }}.html">view section →</a>
    {% else %}
    <span style="font-size:0.8rem; color:#aaa; margin-top:0.4rem; display:inline-block;">report not yet generated</span>
    {% endif %}
  </div>
  {% endfor %}
  </div>
</div>

<footer>Generated by ctd_report v{{ version }} &nbsp;·&nbsp; {{ cruise }} &nbsp;·&nbsp; {{ generated_at }}</footer>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def generate_ctd_report(
    nc_dir: Path,
    profiles_path: Path,
    section_yaml: Path,
    out_dir: Path,
    force: bool = False,
    section_style: str = "pcolormesh",
    vmin_override: Optional[dict[str, float]] = None,
    vmax_override: Optional[dict[str, float]] = None,
) -> None:
    """Generate the full CTD HTML report suite.

    Parameters
    ----------
    nc_dir:
        Directory containing per-cast ``.nc`` files.
    profiles_path:
        Path to compiled ``profiles.nc`` (built by ``cnv_build_profiles.py``).
    section_yaml:
        Path to ``ctd_sections.yaml``.
    out_dir:
        Root output directory (e.g. ``outputs/ctd_report/``).
    force:
        Regenerate all pages even if they already exist.
    section_style:
        ``"pcolormesh"`` or ``"contourf"`` for section and overview figures.
    vmin_override, vmax_override:
        Per-variable colormap limit overrides applied everywhere.
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    cast_files = _select_cast_files(nc_dir)
    if not cast_files:
        print(f"No cast .nc files found in {nc_dir}")
        return

    print(f"Found {len(cast_files)} cast files")
    all_meta = [_read_cast_meta(path) for path in cast_files]
    all_meta_sorted = sorted(
        [m for m in all_meta if m is not None],
        key=lambda m: m["time_start"],
        reverse=True,
    )
    cruise = (
        all_meta_sorted[0].get("cruise", "odb2026") if all_meta_sorted else "odb2026"
    )

    cast_nums_sorted = [m["cast_num"] for m in all_meta_sorted]
    for i, meta in enumerate(all_meta_sorted):
        nc_path = meta["path"]
        prev_num = cast_nums_sorted[i - 1] if i > 0 else None
        next_num = cast_nums_sorted[i + 1] if i < len(all_meta_sorted) - 1 else None
        out = generate_station_page(
            nc_path,
            out_dir,
            all_meta_sorted,
            prev_num=prev_num,
            next_num=next_num,
            force=force,
        )
        status = "ok" if out else "FAILED"
        print(f"  station cast_{meta['cast_num']:03d}: {status}")

    sections_cfg: dict[str, Any] = {}
    if section_yaml.exists():
        with open(section_yaml) as f:
            sections_cfg = yaml.safe_load(f).get("sections", {})

    for sec_name, sec_cfg in sections_cfg.items():
        out = generate_section_page(
            sec_name,
            sec_cfg,
            profiles_path,
            out_dir,
            force=force,
            section_style=section_style,
            vmin_override=vmin_override,
            vmax_override=vmax_override,
        )
        status = "ok" if out else "skipped (profiles.nc missing or no matching casts)"
        print(f"  section {sec_name}: {status}")

    _write_index(
        all_meta_sorted,
        sections_cfg,
        cruise,
        out_dir,
        force,
        profiles_path=profiles_path,
        section_style=section_style,
        vmin_override=vmin_override,
        vmax_override=vmax_override,
    )
    _write_stations_list(all_meta_sorted, cruise, out_dir, sections_cfg=sections_cfg)
    _write_sections_list(sections_cfg, cruise, out_dir, all_meta=all_meta_sorted)
    print(f"\nReport written to {out_dir}/index.html")


# ---------------------------------------------------------------------------
# Page writers
# ---------------------------------------------------------------------------

_OVERVIEW_VARS: list[tuple[str, str]] = [
    ("CT", "Conservative Temperature (°C)"),
    ("SA", "Absolute Salinity (g kg⁻¹)"),
    ("oxygen_1", "O₂ saturation (%)"),
    ("AOU", "O₂ deficit (% sat)"),
    ("fluorescence", "Fluorescence (mg m⁻³)"),
    ("turbidity", "Turbidity (NTU)"),
]


def _write_index(
    all_meta: list[dict[str, Any]],
    sections_cfg: dict[str, Any],
    cruise: str,
    out_dir: Path,
    force: bool,  # noqa: ARG001
    profiles_path: Optional[Path] = None,
    section_style: str = "pcolormesh",
    vmin_override: Optional[dict[str, float]] = None,
    vmax_override: Optional[dict[str, float]] = None,
    cruise_info: Optional[dict[str, Any]] = None,
    timeseries_cfg: Optional[dict[str, Any]] = None,
) -> None:
    """Write index.html with header card, stats, overview map, and stacked property panels."""
    times = [m["time_start"] for m in all_meta if m.get("time_start")]
    times_str = sorted(str(t)[:10] for t in times if t)
    date_range = f"{times_str[0]} – {times_str[-1]}" if len(times_str) >= 2 else "—"

    n_days = 0
    if len(times_str) >= 2:
        from datetime import date

        try:
            d0 = date.fromisoformat(times_str[0])  # earliest
            d1 = date.fromisoformat(times_str[-1])  # latest
            n_days = (d1 - d0).days + 1
        except ValueError:
            pass

    max_depth = max((m.get("max_depth", 0) for m in all_meta), default=0)
    ci = cruise_info or {}

    _valid_lats = [m["lat"] for m in all_meta if np.isfinite(m.get("lat", np.nan))]
    _valid_lons = [m["lon"] for m in all_meta if np.isfinite(m.get("lon", np.nan))]

    # Build combined sections+timeseries data for the map and for overview markers
    _ts_cfg = timeseries_cfg or {}
    _all_groups = {**sections_cfg, **_ts_cfg}
    sections_data_map: list[dict[str, Any]] = []
    # cast_groups: color → set of cast numbers (for overview panel top markers)
    cast_groups: dict[str, list[int]] = {}
    for grp_name, grp_cfg in _all_groups.items():
        cast_nums_grp = _expand_cast_numbers(grp_cfg.get("cast_numbers", []))
        color = grp_cfg.get("color", "#888888")
        if cast_nums_grp:
            cast_groups[color] = cast_groups.get(color, []) + list(cast_nums_grp)

    # For the index map, gather section track positions from all_meta
    cast_pos = {
        m["cast_num"]: (m["lat"], m["lon"])
        for m in all_meta
        if np.isfinite(m.get("lat", np.nan))
    }
    for grp_name, grp_cfg in sections_cfg.items():
        cast_nums_grp = _expand_cast_numbers(grp_cfg.get("cast_numbers", []))
        lats_g = [cast_pos[cn][0] for cn in sorted(cast_nums_grp) if cn in cast_pos]
        lons_g = [cast_pos[cn][1] for cn in sorted(cast_nums_grp) if cn in cast_pos]
        if lats_g:
            sections_data_map.append(
                {
                    "name": grp_name,
                    "color": grp_cfg.get("color", "#888888"),
                    "lats": lats_g,
                    "lons": lons_g,
                }
            )
    for grp_name, grp_cfg in _ts_cfg.items():
        cast_nums_grp = _expand_cast_numbers(grp_cfg.get("cast_numbers", []))
        lats_g = [cast_pos[cn][0] for cn in sorted(cast_nums_grp) if cn in cast_pos]
        lons_g = [cast_pos[cn][1] for cn in sorted(cast_nums_grp) if cn in cast_pos]
        if lats_g:
            sections_data_map.append(
                {
                    "name": grp_name,
                    "color": grp_cfg.get("color", "#888888"),
                    "lats": lats_g,
                    "lons": lons_g,
                }
            )

    fig_map_b64 = (
        _make_all_sections_map_b64(
            sections_data_map,
            _valid_lats,
            _valid_lons,
            legend_outside=True,
        )
        if _valid_lats
        else None
    )

    # Stacked overview panels and cruise T-S diagram from profiles.nc
    overview_panels: list[dict[str, Any]] = []
    ts_b64: Optional[str] = None
    if profiles_path is not None and profiles_path.exists():
        try:
            ds_all = xr.open_dataset(
                profiles_path, decode_timedelta=False, engine="netcdf4"
            ).load()
            ds_all = _add_teos10_profiles(ds_all)
            ds_all = _add_aou(ds_all)

            mask_down = ds_all["cast_type"].values == "down"
            ds_down = ds_all.isel(N_PROF=mask_down)
            order = np.argsort(ds_down["cast_number"].values)
            ds_sorted = ds_down.isel(N_PROF=order)

            lats = ds_sorted["latitude"].values.tolist()
            lons = ds_sorted["longitude"].values.tolist()
            bathy = _interpolate_bathy_at_casts(lats, lons, path=GEBCO_PATH)

            vmin = vmin_override or {}
            vmax = vmax_override or {}
            for var, label in _OVERVIEW_VARS:
                b64 = _make_overview_panel_b64(
                    ds_sorted,
                    var,
                    label,
                    bathy_depths=bathy,
                    style=section_style,
                    vmin=vmin.get(var),
                    vmax=vmax.get(var),
                    cast_groups=cast_groups,
                )
                if b64:
                    overview_panels.append({"title": label, "b64": b64})

            ts_b64 = _make_section_ts_histogram_b64(ds_sorted)
            ds_all.close()
        except Exception:  # noqa: BLE001
            pass  # Overview panels are optional; never crash index generation

    ctx: dict[str, Any] = {
        "cruise": cruise,
        "ship": ci.get("ship", ""),
        "cruise_id": ci.get("cruise_id", ""),
        "project": ci.get("project", ""),
        "date_range": date_range,
        "n_casts": len(all_meta),
        "n_sections": len(sections_cfg),
        "max_depth_str": f"{max_depth:.0f} dbar",
        "n_days": n_days,
        "fig_map_b64": fig_map_b64,
        "overview_panels": overview_panels,
        "ts_b64": ts_b64
        if profiles_path is not None and profiles_path.exists()
        else None,
        "version": _VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }
    env = Environment(autoescape=True)
    html = env.from_string(_INDEX_TEMPLATE).render(**ctx)
    (out_dir / "index.html").write_text(html, encoding="utf-8")


def _dec_min(deg: float, pos_hem: str, neg_hem: str) -> str:
    """Format decimal degrees as degrees-decimal-minutes, e.g. 65°13.782′N."""
    if not np.isfinite(deg):
        return "—"
    hem = pos_hem if deg >= 0 else neg_hem
    deg = abs(deg)
    d = int(deg)
    m = (deg - d) * 60.0
    return f"{d}°{m:06.3f}′{hem}"


_DEPTH_PILL_PALETTE: list[tuple[str, str]] = [
    ("#deebf7", "#1a1a2e"),  # shallowest — very light blue, dark text
    ("#9ecae1", "#1a1a2e"),  # light blue, dark text
    ("#4292c6", "#ffffff"),  # medium blue, white text
    ("#2171b5", "#ffffff"),  # dark blue, white text
    ("#084594", "#ffffff"),  # deepest — very dark blue, white text
]


def _depth_pill_style(depth: float, rounded_max: float) -> tuple[str, str]:
    """Return (background_hex, text_hex) for a depth pill based on 5-class scheme."""
    if rounded_max <= 0 or not np.isfinite(depth):
        return _DEPTH_PILL_PALETTE[0]
    cls = min(4, int(depth / rounded_max * 5))
    return _DEPTH_PILL_PALETTE[cls]


def _round_max_depth(max_depth: float) -> float:
    """Round *max_depth* up to the nearest 100, 500, or 1000 dbar."""
    if max_depth <= 500:
        return float(np.ceil(max_depth / 100) * 100)
    if max_depth <= 2000:
        return float(np.ceil(max_depth / 500) * 500)
    return float(np.ceil(max_depth / 1000) * 1000)


def _write_stations_list(
    all_meta: list[dict[str, Any]],
    cruise: str,
    out_dir: Path,
    sections_cfg: Optional[dict[str, Any]] = None,
    timeseries_cfg: Optional[dict[str, Any]] = None,
    ladcp_dir: Optional[Path] = None,
) -> None:
    """Write station_index.html with cruise map, depth pills, and section/timeseries links."""
    # LADCP: collect cast numbers that have a processed .mat file
    ladcp_cast_nums: set[int] = set()
    if ladcp_dir is not None and ladcp_dir.exists():
        for f in ladcp_dir.glob("*.mat"):
            try:
                ladcp_cast_nums.add(int(f.stem))
            except ValueError:
                pass

    # Section name → YAML color; cast → section names
    section_colors: dict[str, str] = {
        name: cfg.get("color", "#2c6e49") for name, cfg in (sections_cfg or {}).items()
    }
    cast_to_sections: dict[int, list[str]] = {}
    for sec_name, sec_cfg in (sections_cfg or {}).items():
        for cn in _expand_cast_numbers(sec_cfg.get("cast_numbers", [])):
            cast_to_sections.setdefault(cn, []).append(sec_name)

    # Timeseries name → YAML color; cast → timeseries names
    ts_colors: dict[str, str] = {
        name: cfg.get("color", "#7b2d8b")
        for name, cfg in (timeseries_cfg or {}).items()
    }
    cast_to_timeseries: dict[int, list[str]] = {}
    for ts_name, ts_cfg in (timeseries_cfg or {}).items():
        for cn in _expand_cast_numbers(ts_cfg.get("cast_numbers", [])):
            cast_to_timeseries.setdefault(cn, []).append(ts_name)

    all_depths = [
        m.get("max_depth", 0) for m in all_meta if np.isfinite(m.get("max_depth", 0))
    ]
    rounded_max = _round_max_depth(max(all_depths, default=100))

    stations = []
    for m in all_meta:
        lat = m.get("lat", np.nan)
        lon = m.get("lon", np.nan)
        depth = m.get("max_depth", 0)
        bg, fg = _depth_pill_style(float(depth), rounded_max)
        cast_num_int = m["cast_num"]
        stations.append(
            {
                "cast_num": f"{cast_num_int:03d}",
                "filename": m.get("raw_filename", "—"),
                "time_start_str": str(m.get("time_start", ""))[:16].replace("T", " "),
                "lat_str": _dec_min(lat, "N", "S"),
                "lon_str": _dec_min(lon, "E", "W"),
                "max_depth_str": f"{depth:.0f}",
                "depth_bg": bg,
                "depth_fg": fg,
                "sections": [
                    {"name": sn, "color": section_colors.get(sn, "#2c6e49")}
                    for sn in cast_to_sections.get(cast_num_int, [])
                ],
                "timeseries": [
                    {"name": tn, "color": ts_colors.get(tn, "#7b2d8b")}
                    for tn in cast_to_timeseries.get(cast_num_int, [])
                ],
                "ladcp_has": cast_num_int in ladcp_cast_nums,
            }
        )

    ctx: dict[str, Any] = {
        "cruise": cruise,
        "stations": stations,
        "cruise_map_b64": _make_cruise_map_b64(all_meta),
        "ladcp_configured": ladcp_dir is not None,
        "version": _VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }
    env = Environment(autoescape=True)
    html = env.from_string(_STATIONS_TEMPLATE).render(**ctx)
    (out_dir / "station_index.html").write_text(html, encoding="utf-8")


def _write_sections_list(
    sections_cfg: dict[str, Any],
    cruise: str,
    out_dir: Path,
    all_meta: Optional[list[dict[str, Any]]] = None,
    ladcp_dir: Optional[Path] = None,
) -> None:
    """Write sections.html with overview map and cards for each section."""
    ladcp_cast_nums: set[int] = set()
    if ladcp_dir is not None and ladcp_dir.exists():
        for f in ladcp_dir.glob("*.mat"):
            try:
                ladcp_cast_nums.add(int(f.stem))
            except ValueError:
                pass

    # Build cast → position lookup for the overview map
    cast_pos: dict[int, tuple[float, float]] = {}
    if all_meta:
        for m in all_meta:
            cn = m.get("cast_num")
            if (
                cn is not None
                and np.isfinite(m.get("lat", np.nan))
                and np.isfinite(m.get("lon", np.nan))
            ):
                cast_pos[int(cn)] = (float(m["lat"]), float(m["lon"]))

    sections = []
    sections_data: list[dict[str, Any]] = []
    for name, cfg in sections_cfg.items():
        cast_nums = _expand_cast_numbers(cfg.get("cast_numbers", []))
        report_path = out_dir / "sections" / f"section_{name}.html"
        ladcp_has = any(c in ladcp_cast_nums for c in cast_nums)
        sections.append(
            {
                "name": name,
                "description": cfg.get("description", ""),
                "color": cfg.get("color", "#1a3a5c"),
                "n_casts": len(cast_nums),
                "cast_range": _compact_cast_list(cast_nums) if cast_nums else "—",
                "report_exists": report_path.exists(),
                "ladcp_has": ladcp_has,
            }
        )
        if cast_pos:
            sec_lats = [cast_pos[c][0] for c in cast_nums if c in cast_pos]
            sec_lons = [cast_pos[c][1] for c in cast_nums if c in cast_pos]
            if sec_lats:
                sections_data.append(
                    {
                        "name": name,
                        "color": cfg.get("color", "#555555"),
                        "lats": sec_lats,
                        "lons": sec_lons,
                    }
                )

    all_cast_lats = [v[0] for v in cast_pos.values()]
    all_cast_lons = [v[1] for v in cast_pos.values()]
    sections_map_b64 = (
        _make_all_sections_map_b64(sections_data, all_cast_lats, all_cast_lons)
        if sections_data
        else None
    )

    ctx: dict[str, Any] = {
        "cruise": cruise,
        "sections": sections,
        "sections_map_b64": sections_map_b64,
        "ladcp_configured": ladcp_dir is not None,
        "version": _VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }
    env = Environment(autoescape=True)
    html = env.from_string(_SECTIONS_TEMPLATE).render(**ctx)
    (out_dir / "sections.html").write_text(html, encoding="utf-8")


_TIMESERIES_LIST_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Timeseries — {{ cruise }}</title>
<style>
  :root { --ocean: #1a3a5c; --seafoam: #e8f4f8; --accent: #2e86ab; --text: #1a1a2e; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #f5f7fa; color: var(--text); }
  header { background: var(--ocean); color: #fff; padding: 1rem 1.5rem; }
  header h1 { font-size: 1.3rem; }
  nav { background: var(--seafoam); padding: 0.6rem 1.5rem; border-bottom: 1px solid #cdd8e3; }
  nav a { color: var(--ocean); text-decoration: none; font-size: 0.9rem; margin-right: 0.5rem; }
  nav a:hover { text-decoration: underline; }
  nav span { color: #888; font-size: 0.9rem; margin-right: 0.5rem; }
  .content-row {
    display: flex; gap: 1.5rem; margin: 1rem 1.5rem; align-items: flex-start;
  }
  .map-sidebar { flex: 0 0 auto; max-width: 400px; }
  .map-sidebar img { width: 100%; height: auto; border-radius: 4px; }
  .grid {
    flex: 1;
    display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
    gap: 1rem;
  }
  .ts-card {
    background: #fff; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    padding: 1.1rem; border-left: 4px solid #1a3a5c;
  }
  .ts-card h3 { font-size: 1rem; color: var(--ocean); margin-bottom: 0.3rem; }
  .ts-card .desc { font-size: 0.85rem; color: #555; margin-bottom: 0.6rem; }
  .ts-card .info { font-size: 0.82rem; color: #777; }
  .btn {
    display: inline-block; background: var(--ocean); color: #fff;
    padding: 0.3rem 0.85rem; border-radius: 999px; text-decoration: none;
    font-size: 0.82rem; margin-top: 0.6rem;
  }
  .btn:hover { background: var(--accent); }
  .ladcp-yes { display:inline-block; padding:0.18rem 0.5rem; border-radius:999px; font-size:0.75rem; font-weight:600; background:#2c6e49; color:#fff; }
  .ladcp-no  { display:inline-block; padding:0.18rem 0.5rem; border-radius:999px; font-size:0.75rem; font-weight:600; background:#c0392b; color:#fff; }
  footer { text-align: center; padding: 1rem; font-size: 0.75rem; color: #999; }
</style>
</head>
<body>
<header><h1>Timeseries — {{ cruise }}</h1></header>
<nav>
  <a href="index.html">Index</a> <span>›</span>
  <span>Timeseries</span>
</nav>
<div class="content-row">
  {% if timeseries_map_b64 %}
  <div class="map-sidebar">
    <img src="data:image/png;base64,{{ timeseries_map_b64 }}" alt="Timeseries locations map">
  </div>
  {% endif %}
  <div class="grid">
  {% for ts in timeseries %}
  <div class="ts-card" style="border-left-color: {{ ts.color }}">
    <h3>{{ ts.name }}</h3>
    <div class="desc">{{ ts.description }}</div>
    <div class="info">{{ ts.n_casts }} casts &nbsp;·&nbsp; casts {{ ts.cast_range }}</div>
    {% if ladcp_configured %}
    <div style="margin-top:0.4rem;">
      {% if ts.ladcp_has %}<span class="ladcp-yes">✓ LADCP</span>{% else %}<span class="ladcp-no">– LADCP</span>{% endif %}
    </div>
    {% endif %}
    {% if ts.report_exists %}
    <a class="btn" href="timeseries/timeseries_{{ ts.name }}.html">view timeseries →</a>
    {% else %}
    <span style="font-size:0.8rem; color:#aaa; margin-top:0.4rem; display:inline-block;">report not yet generated</span>
    {% endif %}
  </div>
  {% endfor %}
  {% if not timeseries %}
  <div style="color:#888">No timeseries groups configured.</div>
  {% endif %}
  </div>
</div>
<footer>Generated by ctd_report v{{ version }} &nbsp;·&nbsp; {{ cruise }} &nbsp;·&nbsp; {{ generated_at }}</footer>
</body>
</html>"""


def _write_timeseries_list(
    timeseries_cfg: dict[str, Any],
    cruise: str,
    out_dir: Path,
    all_meta: Optional[list[dict[str, Any]]] = None,
    ladcp_dir: Optional[Path] = None,
) -> None:
    """Write timeseries.html listing all timeseries groups with an overview map."""
    from ctd_report._section import _expand_cast_numbers

    ladcp_cast_nums: set[int] = set()
    if ladcp_dir is not None and ladcp_dir.exists():
        for f in ladcp_dir.glob("*.mat"):
            try:
                ladcp_cast_nums.add(int(f.stem))
            except ValueError:
                pass

    # Build cast → position lookup
    cast_pos: dict[int, tuple[float, float]] = {}
    if all_meta:
        for m in all_meta:
            cn = m.get("cast_num")
            if (
                cn is not None
                and np.isfinite(m.get("lat", np.nan))
                and np.isfinite(m.get("lon", np.nan))
            ):
                cast_pos[int(cn)] = (float(m["lat"]), float(m["lon"]))

    items = []
    timeseries_data: list[dict[str, Any]] = []
    for name, cfg in timeseries_cfg.items():
        cast_nums = _expand_cast_numbers(cfg.get("cast_numbers", []))
        report_path = out_dir / "timeseries" / f"timeseries_{name}.html"
        color = cfg.get("color", "#7b2d8b")
        ladcp_has = any(c in ladcp_cast_nums for c in cast_nums)
        items.append(
            {
                "name": name,
                "description": cfg.get("description", ""),
                "color": color,
                "n_casts": len(cast_nums),
                "cast_range": _compact_cast_list(cast_nums) if cast_nums else "—",
                "report_exists": report_path.exists(),
                "ladcp_has": ladcp_has,
            }
        )
        if cast_pos:
            ts_lats = [cast_pos[c][0] for c in cast_nums if c in cast_pos]
            ts_lons = [cast_pos[c][1] for c in cast_nums if c in cast_pos]
            if ts_lats:
                timeseries_data.append(
                    {"name": name, "color": color, "lats": ts_lats, "lons": ts_lons}
                )

    all_cast_lats = [v[0] for v in cast_pos.values()]
    all_cast_lons = [v[1] for v in cast_pos.values()]
    timeseries_map_b64 = (
        _make_all_sections_map_b64(timeseries_data, all_cast_lats, all_cast_lons)
        if timeseries_data
        else None
    )

    ctx: dict[str, Any] = {
        "cruise": cruise,
        "timeseries": items,
        "timeseries_map_b64": timeseries_map_b64,
        "ladcp_configured": ladcp_dir is not None,
        "version": _VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }
    env = Environment(autoescape=True)
    html = env.from_string(_TIMESERIES_LIST_TEMPLATE).render(**ctx)
    (out_dir / "timeseries.html").write_text(html, encoding="utf-8")


# ---------------------------------------------------------------------------
# Metadata helpers
# ---------------------------------------------------------------------------


def _select_cast_files(nc_dir: Path) -> list[Path]:
    """Return sorted list of cast .nc files, preferring _b variants."""
    pattern = re.compile(r"^mixsed2_(\d+)(_b)?$")
    chosen: dict[int, Path] = {}
    for p in sorted(nc_dir.glob("*.nc")):
        m = pattern.match(p.stem)
        if not m:
            continue
        cast_num = int(m.group(1))
        is_b = m.group(2) is not None
        if cast_num not in chosen or is_b:
            chosen[cast_num] = p
    return [chosen[k] for k in sorted(chosen)]


def _read_cast_meta(nc_path: Path) -> Optional[dict[str, Any]]:
    """Read scalar metadata from a cast .nc file without loading all data."""
    try:
        ds = xr.open_dataset(nc_path, decode_timedelta=False, engine="netcdf4")
        cast_num = int(re.search(r"_(\d+)(_b)?\.nc$", nc_path.name).group(1))  # type: ignore[union-attr]
        lat = float(np.nanmedian(ds["latitude"].values))
        lon = float(np.nanmedian(ds["longitude"].values))
        max_depth = float(np.nanmax(ds["pressure"].values))
        time_start = ds["time"].values[0]
        time_end = ds["time"].values[-1]
        raw_filename = ds.attrs.get("raw_filename", nc_path.stem + ".cnv")
        cruise = ds.attrs.get("cruise", "odb2026")
        ds.close()
        return {
            "cast_num": cast_num,
            "path": nc_path,
            "lat": lat,
            "lon": lon,
            "max_depth": max_depth,
            "time_start": time_start,
            "time_end": time_end,
            "raw_filename": raw_filename,
            "cruise": cruise,
        }
    except Exception:  # noqa: BLE001
        return None
