"""Tier-3: entry point — generates index, stations list, and sections list pages."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Optional

import numpy as np
import xarray as xr
import yaml
from jinja2 import Environment

from ctd_report._plots import _make_station_map_b64
from ctd_report._section import _expand_cast_numbers, generate_section_page
from ctd_report._station import generate_station_page
from ctd_report._timeseries import generate_timeseries_page

# ---------------------------------------------------------------------------
# HTML templates
# ---------------------------------------------------------------------------

_INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CTD Report — {{ cruise }}</title>
<style>
  :root { --ocean: #1a3a5c; --seafoam: #e8f4f8; --accent: #2e86ab; --text: #1a1a2e; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #f5f7fa; color: var(--text); }
  header { background: var(--ocean); color: #fff; padding: 1.25rem 1.5rem; }
  header h1 { font-size: 1.5rem; }
  header .meta { font-size: 0.9rem; opacity: 0.8; margin-top: 0.3rem; }
  .card {
    background: #fff; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    padding: 1.25rem; margin: 1rem 1.5rem;
  }
  .card h2 { font-size: 1.05rem; color: var(--ocean); margin-bottom: 0.75rem; }
  .hero { display: flex; gap: 1.5rem; align-items: flex-start; flex-wrap: wrap; }
  .hero img { max-height: 360px; width: auto; border-radius: 6px; }
  .hero-stats { display: grid; grid-template-columns: 1fr 1fr; gap: 0.75rem; min-width: 200px; }
  .stat { background: var(--seafoam); border-radius: 6px; padding: 0.75rem; text-align: center; }
  .stat .n { font-size: 2rem; font-weight: 700; color: var(--ocean); }
  .stat .lbl { font-size: 0.8rem; color: #555; }
  .btn {
    display: inline-block; background: var(--ocean); color: #fff;
    padding: 0.4rem 1.1rem; border-radius: 999px; text-decoration: none;
    font-size: 0.9rem; margin: 0.3rem;
  }
  .btn:hover { background: var(--accent); }
  .btn-sec { background: #2c6e49; }
  .btn-ts  { background: #7b2d8b; }
  footer { text-align: center; padding: 1rem; font-size: 0.75rem; color: #999; }
</style>
</head>
<body>

<header>
  <h1>CTD Report — {{ cruise }}</h1>
  <div class="meta">{{ date_range }} &nbsp;·&nbsp; {{ n_casts }} casts &nbsp;·&nbsp; {{ n_sections }} sections</div>
</header>

<div class="card">
  <div class="hero">
    {% if fig_map_b64 %}
    <img src="data:image/png;base64,{{ fig_map_b64 }}" alt="Station map">
    {% endif %}
    <div>
      <div class="hero-stats">
        <div class="stat"><div class="n">{{ n_casts }}</div><div class="lbl">CTD casts</div></div>
        <div class="stat"><div class="n">{{ n_sections }}</div><div class="lbl">Sections</div></div>
        <div class="stat"><div class="n">{{ max_depth_str }}</div><div class="lbl">Max depth</div></div>
        <div class="stat"><div class="n">{{ n_days }}</div><div class="lbl">Days at sea</div></div>
      </div>
      <div style="margin-top:1rem;">
        <a class="btn" href="station_index.html">All stations</a>
        <a class="btn btn-sec" href="sections.html">Sections</a>
        <a class="btn btn-ts" href="timeseries.html">Time series</a>
      </div>
    </div>
  </div>
</div>

<footer>Generated by ctd_report &nbsp;·&nbsp; {{ cruise }}</footer>
</body>
</html>"""


_STATIONS_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Station index — {{ cruise }}</title>
<style>
  :root { --ocean: #1a3a5c; --seafoam: #e8f4f8; --accent: #2e86ab; --text: #1a1a2e; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #f5f7fa; color: var(--text); }
  header { background: var(--ocean); color: #fff; padding: 1rem 1.5rem; }
  header h1 { font-size: 1.3rem; }
  nav { background: var(--seafoam); padding: 0.6rem 1.5rem; border-bottom: 1px solid #cdd8e3; }
  nav a { color: var(--ocean); text-decoration: none; font-size: 0.9rem; margin-right: 0.5rem; }
  nav a:hover { text-decoration: underline; }
  nav span { color: #888; font-size: 0.9rem; margin-right: 0.5rem; }
  .card {
    background: #fff; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    padding: 1.25rem; margin: 1rem 1.5rem; overflow-x: auto;
  }
  table { width: 100%; border-collapse: collapse; font-size: 0.88rem; white-space: nowrap; }
  th {
    background: var(--ocean); color: #fff; padding: 0.5rem 0.75rem;
    text-align: left; position: sticky; top: 0; z-index: 1;
  }
  td { padding: 0.42rem 0.75rem; border-bottom: 1px solid #eee; }
  tbody tr { cursor: pointer; }
  tbody tr:hover td { background: var(--seafoam); }
  .cast-link { color: var(--ocean); font-weight: 600; text-decoration: none; }
  .cast-link:hover { text-decoration: underline; }
  .filename { font-family: monospace; font-size: 0.82rem; color: #444; }
  footer { text-align: center; padding: 1rem; font-size: 0.75rem; color: #999; }
</style>
</head>
<body>

<header><h1>Station index — {{ cruise }} ({{ stations|length }} casts)</h1></header>

<nav>
  <a href="index.html">Index</a> <span>›</span>
  <span>Stations</span>
</nav>

<div class="card">
  <table>
    <thead>
      <tr>
        <th>Cast</th>
        <th>File</th>
        <th>Start (UTC)</th>
        <th>End (UTC)</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Max depth (dbar)</th>
      </tr>
    </thead>
    <tbody>
    {% for s in stations %}
      <tr onclick="window.location='stations/cast_{{ s.cast_num }}.html'">
        <td><a class="cast-link" href="stations/cast_{{ s.cast_num }}.html">{{ s.cast_num }}</a></td>
        <td class="filename">{{ s.filename }}</td>
        <td>{{ s.time_start_str }}</td>
        <td>{{ s.time_end_str }}</td>
        <td>{{ s.lat_str }}</td>
        <td>{{ s.lon_str }}</td>
        <td>{{ s.max_depth_str }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

<footer>Generated by ctd_report &nbsp;·&nbsp; {{ cruise }}</footer>
</body>
</html>"""


_SECTIONS_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sections — {{ cruise }}</title>
<style>
  :root { --ocean: #1a3a5c; --seafoam: #e8f4f8; --accent: #2e86ab; --text: #1a1a2e; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #f5f7fa; color: var(--text); }
  header { background: var(--ocean); color: #fff; padding: 1rem 1.5rem; }
  header h1 { font-size: 1.3rem; }
  nav { background: var(--seafoam); padding: 0.6rem 1.5rem; border-bottom: 1px solid #cdd8e3; }
  nav a { color: var(--ocean); text-decoration: none; font-size: 0.9rem; margin-right: 0.5rem; }
  nav a:hover { text-decoration: underline; }
  nav span { color: #888; font-size: 0.9rem; margin-right: 0.5rem; }
  .grid {
    display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1rem; margin: 1rem 1.5rem;
  }
  .sec-card {
    background: #fff; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    padding: 1.1rem; border-left: 4px solid #1a3a5c;
  }
  .sec-card h3 { font-size: 1rem; color: var(--ocean); margin-bottom: 0.3rem; }
  .sec-card .desc { font-size: 0.85rem; color: #555; margin-bottom: 0.6rem; }
  .sec-card .info { font-size: 0.82rem; color: #777; }
  .btn {
    display: inline-block; background: var(--ocean); color: #fff;
    padding: 0.3rem 0.85rem; border-radius: 999px; text-decoration: none;
    font-size: 0.82rem; margin-top: 0.6rem;
  }
  .btn:hover { background: var(--accent); }
  footer { text-align: center; padding: 1rem; font-size: 0.75rem; color: #999; }
</style>
</head>
<body>

<header><h1>Sections — {{ cruise }}</h1></header>

<nav>
  <a href="index.html">Index</a> <span>›</span>
  <span>Sections</span>
</nav>

<div class="grid">
{% for sec in sections %}
<div class="sec-card" style="border-left-color: {{ sec.color }}">
  <h3>{{ sec.name }}</h3>
  <div class="desc">{{ sec.description }}</div>
  <div class="info">{{ sec.n_casts }} casts &nbsp;·&nbsp; casts {{ sec.cast_range }}</div>
  {% if sec.report_exists %}
  <a class="btn" href="sections/section_{{ sec.name }}.html">view section →</a>
  {% else %}
  <span style="font-size:0.8rem; color:#aaa; margin-top:0.4rem; display:inline-block;">report not yet generated</span>
  {% endif %}
</div>
{% endfor %}
</div>

<footer>Generated by ctd_report &nbsp;·&nbsp; {{ cruise }}</footer>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def generate_ctd_report(
    nc_dir: Path,
    profiles_path: Path,
    section_yaml: Path,
    out_dir: Path,
    force: bool = False,
) -> None:
    """Generate the full CTD HTML report suite.

    Parameters
    ----------
    nc_dir:
        Directory containing per-cast ``.nc`` files.
    profiles_path:
        Path to compiled ``profiles.nc`` (built by ``cnv_build_profiles.py``).
    section_yaml:
        Path to ``ctd_sections.yaml``.
    out_dir:
        Root output directory (e.g. ``outputs/ctd_report/``).
    force:
        Regenerate all pages even if they already exist.
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    cast_files = _select_cast_files(nc_dir)
    if not cast_files:
        print(f"No cast .nc files found in {nc_dir}")
        return

    print(f"Found {len(cast_files)} cast files")
    all_meta = [_read_cast_meta(path) for path in cast_files]
    all_meta_sorted = sorted(
        [m for m in all_meta if m is not None],
        key=lambda m: m["time_start"],
        reverse=True,
    )
    cruise = all_meta_sorted[0].get("cruise", "odb2026") if all_meta_sorted else "odb2026"

    cast_nums_sorted = [m["cast_num"] for m in all_meta_sorted]
    for i, meta in enumerate(all_meta_sorted):
        nc_path = meta["path"]
        prev_num = cast_nums_sorted[i - 1] if i > 0 else None
        next_num = cast_nums_sorted[i + 1] if i < len(all_meta_sorted) - 1 else None
        out = generate_station_page(
            nc_path, out_dir, all_meta_sorted,
            prev_num=prev_num, next_num=next_num, force=force,
        )
        status = "ok" if out else "FAILED"
        print(f"  station cast_{meta['cast_num']:03d}: {status}")

    sections_cfg: dict[str, Any] = {}
    if section_yaml.exists():
        with open(section_yaml) as f:
            sections_cfg = yaml.safe_load(f).get("sections", {})

    for sec_name, sec_cfg in sections_cfg.items():
        out = generate_section_page(sec_name, sec_cfg, profiles_path, out_dir, force=force)
        status = "ok" if out else "skipped (profiles.nc missing or no matching casts)"
        print(f"  section {sec_name}: {status}")

    out = generate_timeseries_page(profiles_path, out_dir, force=force)
    print(f"  timeseries: {'ok' if out else 'skipped (profiles.nc missing)'}")

    _write_index(all_meta_sorted, sections_cfg, cruise, out_dir, force)
    _write_stations_list(all_meta_sorted, cruise, out_dir)
    _write_sections_list(sections_cfg, cruise, out_dir)
    print(f"\nReport written to {out_dir}/index.html")


# ---------------------------------------------------------------------------
# Page writers
# ---------------------------------------------------------------------------

def _write_index(
    all_meta: list[dict[str, Any]],
    sections_cfg: dict[str, Any],
    cruise: str,
    out_dir: Path,
    force: bool,  # noqa: ARG001
) -> None:
    """Write index.html with header card, stats, and overview map."""
    times = [m["time_start"] for m in all_meta if m.get("time_start")]
    times_str = sorted(str(t)[:10] for t in times if t)
    date_range = f"{times_str[-1]} – {times_str[0]}" if len(times_str) >= 2 else "—"

    n_days = 0
    if len(times_str) >= 2:
        from datetime import date
        try:
            d0 = date.fromisoformat(times_str[-1])
            d1 = date.fromisoformat(times_str[0])
            n_days = (d1 - d0).days + 1
        except ValueError:
            pass

    max_depth = max((m.get("max_depth", 0) for m in all_meta), default=0)

    fig_map_b64 = _make_station_map_b64(
        lat=float(np.nanmean([m["lat"] for m in all_meta if np.isfinite(m.get("lat", np.nan))])),
        lon=float(np.nanmean([m["lon"] for m in all_meta if np.isfinite(m.get("lon", np.nan))])),
        all_meta=all_meta,
    )

    ctx: dict[str, Any] = {
        "cruise": cruise,
        "date_range": date_range,
        "n_casts": len(all_meta),
        "n_sections": len(sections_cfg),
        "max_depth_str": f"{max_depth:.0f} dbar",
        "n_days": n_days,
        "fig_map_b64": fig_map_b64,
    }
    env = Environment(autoescape=True)
    html = env.from_string(_INDEX_TEMPLATE).render(**ctx)
    (out_dir / "index.html").write_text(html, encoding="utf-8")


def _dec_min(deg: float, pos_hem: str, neg_hem: str) -> str:
    """Format decimal degrees as degrees-decimal-minutes, e.g. 65°13.782′N."""
    if not np.isfinite(deg):
        return "—"
    hem = pos_hem if deg >= 0 else neg_hem
    deg = abs(deg)
    d = int(deg)
    m = (deg - d) * 60.0
    return f"{d}°{m:06.3f}′{hem}"


def _write_stations_list(
    all_meta: list[dict[str, Any]],
    cruise: str,
    out_dir: Path,
) -> None:
    """Write station_index.html — latest-first table with filename, times, dec-min position."""
    stations = []
    for m in all_meta:
        lat = m.get("lat", np.nan)
        lon = m.get("lon", np.nan)
        stations.append({
            "cast_num": f"{m['cast_num']:03d}",
            "filename": m.get("raw_filename", "—"),
            "time_start_str": str(m.get("time_start", ""))[:16].replace("T", " "),
            "time_end_str": str(m.get("time_end", ""))[:16].replace("T", " "),
            "lat_str": _dec_min(lat, "N", "S"),
            "lon_str": _dec_min(lon, "E", "W"),
            "max_depth_str": f"{m.get('max_depth', 0):.0f}",
        })
    ctx: dict[str, Any] = {"cruise": cruise, "stations": stations}
    env = Environment(autoescape=True)
    html = env.from_string(_STATIONS_TEMPLATE).render(**ctx)
    (out_dir / "station_index.html").write_text(html, encoding="utf-8")


def _write_sections_list(
    sections_cfg: dict[str, Any],
    cruise: str,
    out_dir: Path,
) -> None:
    """Write sections.html with cards for each section."""
    sections = []
    for name, cfg in sections_cfg.items():
        cast_nums = _expand_cast_numbers(cfg.get("cast_numbers", []))
        report_path = out_dir / "sections" / f"section_{name}.html"
        sections.append({
            "name": name,
            "description": cfg.get("description", ""),
            "color": cfg.get("color", "#1a3a5c"),
            "n_casts": len(cast_nums),
            "cast_range": f"{min(cast_nums)}–{max(cast_nums)}" if cast_nums else "—",
            "report_exists": report_path.exists(),
        })

    ctx: dict[str, Any] = {"cruise": cruise, "sections": sections}
    env = Environment(autoescape=True)
    html = env.from_string(_SECTIONS_TEMPLATE).render(**ctx)
    (out_dir / "sections.html").write_text(html, encoding="utf-8")


# ---------------------------------------------------------------------------
# Metadata helpers
# ---------------------------------------------------------------------------

def _select_cast_files(nc_dir: Path) -> list[Path]:
    """Return sorted list of cast .nc files, preferring _b variants."""
    pattern = re.compile(r"^mixsed2_(\d+)(_b)?$")
    chosen: dict[int, Path] = {}
    for p in sorted(nc_dir.glob("*.nc")):
        m = pattern.match(p.stem)
        if not m:
            continue
        cast_num = int(m.group(1))
        is_b = m.group(2) is not None
        if cast_num not in chosen or is_b:
            chosen[cast_num] = p
    return [chosen[k] for k in sorted(chosen)]


def _read_cast_meta(nc_path: Path) -> Optional[dict[str, Any]]:
    """Read scalar metadata from a cast .nc file without loading all data."""
    try:
        ds = xr.open_dataset(nc_path, decode_timedelta=False)
        cast_num = int(re.search(r"_(\d+)(_b)?\.nc$", nc_path.name).group(1))  # type: ignore[union-attr]
        lat = float(np.nanmedian(ds["latitude"].values))
        lon = float(np.nanmedian(ds["longitude"].values))
        max_depth = float(np.nanmax(ds["pressure"].values))
        time_start = ds["time"].values[0]
        time_end = ds["time"].values[-1]
        raw_filename = ds.attrs.get("raw_filename", nc_path.stem + ".cnv")
        cruise = ds.attrs.get("cruise", "odb2026")
        ds.close()
        return {
            "cast_num": cast_num,
            "path": nc_path,
            "lat": lat,
            "lon": lon,
            "max_depth": max_depth,
            "time_start": time_start,
            "time_end": time_end,
            "raw_filename": raw_filename,
            "cruise": cruise,
        }
    except Exception:  # noqa: BLE001
        return None
