"""Shared Jinja2 HTML fragment constants.

Edit FOOTER_LINE once to change the footer across all generated pages.
"""

from __future__ import annotations

FOOTER_LINE = (
    '<footer>Generated by '
    '<a href="http://github.com/eleanorfrajka/oceancast">oceancast</a>'
    " v{{ version }} &nbsp;·&nbsp; {{ cruise }} &nbsp;·&nbsp; {{ generated_at }}"
    "</footer>"
)

#: Convenience tail for templates that end immediately after the footer.
FOOTER_TAIL = FOOTER_LINE + "\n</body>\n</html>"
