"""Tier-2: per-group timeseries HTML report pages.

A timeseries in this codebase is a named group of repeat casts at one location
(yoyo CTDs, e.g. 24 h of repeated profiles).  Config is analogous to sections:
a name, a description, and a list of cast numbers.

The cruise-wide stacked overview plots (all casts, station-number x-axis) live on
index.html, generated by _index.py.  They are not timeseries pages.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

import numpy as np
import xarray as xr
from jinja2 import Environment

from ctd_report._analysis import _add_aou, _add_teos10_profiles, _compact_cast_list
from ctd_report._plots import _make_station_map_b64, _make_timeseries_b64
from ctd_report._section import _expand_cast_numbers

# ---------------------------------------------------------------------------
# Variables to plot (in order)
# ---------------------------------------------------------------------------

_TIMESERIES_VARS: list[tuple[str, str]] = [
    ("CT", "Conservative Temperature (°C)"),
    ("SA", "Absolute Salinity (g kg⁻¹)"),
    ("oxygen_1", "O₂ saturation (%)"),
    ("AOU", "O₂ deficit (% sat)"),
    ("fluorescence", "Fluorescence (mg m⁻³)"),
    ("turbidity", "Turbidity (NTU)"),
]

# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

_TIMESERIES_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ ts_name }} timeseries — {{ cruise }}</title>
<style>
  :root { --ocean: #1a3a5c; --seafoam: #e8f4f8; --accent: #2e86ab; --text: #1a1a2e; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #f5f7fa; color: var(--text); }
  header { background: var(--ocean); color: #fff; padding: 1rem 1.5rem; }
  header h1 { font-size: 1.3rem; }
  header .meta { font-size: 0.85rem; opacity: 0.8; margin-top: 0.25rem; }
  nav { background: var(--seafoam); padding: 0.5rem 1.5rem; border-bottom: 1px solid #cdd8e3;
        display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 0.4rem; }
  nav .breadcrumb a { color: var(--ocean); text-decoration: none; font-size: 0.9rem; margin-right: 0.3rem; }
  nav .breadcrumb a:hover { text-decoration: underline; }
  nav .breadcrumb span { color: #888; font-size: 0.9rem; margin-right: 0.3rem; }
  .legend { font-size: 0.82rem; color: #555; }
  .legend span { display: inline-block; width: 0.8rem; text-align: center; margin-right: 0.15rem; }
  .card {
    background: #fff; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    padding: 1.25rem; margin: 1rem 1.5rem;
  }
  .card h2 { font-size: 1rem; color: var(--ocean); margin-bottom: 0.75rem; }
  .plot-wide { margin-top: 0.5rem; }
  .plot-wide img { max-width: 100%; height: auto; border-radius: 4px; }
  footer { text-align: center; padding: 1rem; font-size: 0.75rem; color: #999; }
</style>
</head>
<body>

<header>
  <h1>{{ ts_name }} — {{ cruise }}</h1>
  <div class="meta">{{ ts_description }} &nbsp;·&nbsp; {{ n_casts }} casts &nbsp;·&nbsp; casts {{ cast_list_str }} &nbsp;·&nbsp; {{ time_range }}</div>
</header>

<nav>
  <div class="breadcrumb">
    <a href="../index.html">Index</a> <span>›</span>
    <a href="../timeseries.html">Timeseries</a> <span>›</span>
    <span>{{ ts_name }}</span>
  </div>
  <div class="legend">
    <span style="color:#1f77b4">▼</span> downcast &nbsp;
    <span style="color:#d62728">▲</span> upcast
  </div>
</nav>

{% if fig_location_b64 %}
<div class="card" style="display:flex;align-items:flex-start;gap:1rem;">
  <img src="data:image/png;base64,{{ fig_location_b64 }}" alt="Yoyo location map" style="max-height:260px;width:auto;border-radius:4px;flex-shrink:0;">
  <div style="font-size:0.85rem;color:#555;padding-top:0.5rem;">
    <strong>{{ ts_name }}</strong><br>
    {{ ts_description }}<br><br>
    {{ n_casts }} casts &nbsp;·&nbsp; casts {{ cast_list_str }}<br>
    {{ time_range }}
  </div>
</div>
{% endif %}

{% for panel in panels %}
{% if panel.b64 %}
<div class="card">
  <h2>{{ panel.title }}</h2>
  <div class="plot-wide">
    <img src="data:image/png;base64,{{ panel.b64 }}" alt="{{ panel.title }}">
  </div>
</div>
{% endif %}
{% endfor %}

{% if not panels %}
<div class="card"><p style="color:#888">No data available for these casts.</p></div>
{% endif %}

<footer>Generated by ctd_report &nbsp;·&nbsp; {{ cruise }}</footer>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Public function
# ---------------------------------------------------------------------------


def generate_timeseries_page(
    ts_name: str,
    ts_cfg: dict,
    profiles_path: Path,
    out_dir: Path,
    force: bool = False,
    section_style: str = "pcolormesh",
    vmin_override: Optional[dict[str, float]] = None,
    vmax_override: Optional[dict[str, float]] = None,
    all_meta: Optional[list[dict]] = None,
) -> Optional[Path]:
    """Generate a per-timeseries HTML page for a named group of repeat casts.

    Plots both downcast and upcast profiles sorted by time_start on a shared
    time x-axis.  Output: ``<out_dir>/timeseries/timeseries_<ts_name>.html``.

    Parameters
    ----------
    ts_name:
        Group name (used in filename and page title).
    ts_cfg:
        Dict with ``cast_numbers``, ``description``, and ``color`` keys.
    profiles_path:
        Path to ``profiles.nc``.
    out_dir:
        Root output directory.
    force:
        Overwrite existing file if True.
    section_style:
        ``"pcolormesh"`` or ``"contourf"``.
    vmin_override, vmax_override:
        Per-variable colormap limit overrides.
    all_meta:
        List of per-cast metadata dicts (keys ``lat``, ``lon``, ``cast_num``);
        used to render a cruise-context location map.  If None, no map is shown.

    Returns
    -------
    Path to the written HTML file, or None if skipped or failed.
    """
    out_file = out_dir / "timeseries" / f"timeseries_{ts_name}.html"
    if out_file.exists() and not force:
        return out_file
    out_file.parent.mkdir(parents=True, exist_ok=True)

    cast_nums = _expand_cast_numbers(ts_cfg.get("cast_numbers", []))
    if not cast_nums:
        return None

    if not profiles_path.exists():
        return None

    try:
        ds_all = xr.open_dataset(
            profiles_path, decode_timedelta=False, engine="netcdf4"
        ).load()
    except Exception:  # noqa: BLE001
        return None

    all_cast_nums = ds_all["cast_number"].values
    mask = np.isin(all_cast_nums, cast_nums)
    if not mask.any():
        ds_all.close()
        return None

    ds_ts = ds_all.isel(N_PROF=mask)
    ds_ts = _add_teos10_profiles(ds_ts)
    ds_ts = _add_aou(ds_ts)

    # Sort all profiles (both down and up) by time_start
    order = np.argsort(ds_ts["time_start"].values)
    ds_ts = ds_ts.isel(N_PROF=order)

    cruise: str = ds_all.attrs.get("cruise", "odb2026")
    n_profiles = int(mask.sum())
    n_casts = len(cast_nums)

    times = ds_ts["time_start"].values
    time_start_str = str(times[0])[:16].replace("T", " ")
    time_end_str = str(times[-1])[:16].replace("T", " ")

    # Location map: centroid of the yoyo station highlighted against all cruise casts
    yoyo_lats = ds_ts["latitude"].values if "latitude" in ds_ts else np.array([])
    yoyo_lons = ds_ts["longitude"].values if "longitude" in ds_ts else np.array([])
    yoyo_lat = float(np.nanmedian(yoyo_lats)) if len(yoyo_lats) else float("nan")
    yoyo_lon = float(np.nanmedian(yoyo_lons)) if len(yoyo_lons) else float("nan")
    fig_location_b64: Optional[str] = None
    if all_meta and np.isfinite(yoyo_lat) and np.isfinite(yoyo_lon):
        fig_location_b64 = _make_station_map_b64(yoyo_lat, yoyo_lon, all_meta)

    vmin = vmin_override or {}
    vmax = vmax_override or {}
    panels: list[dict[str, Any]] = []
    for var, label in _TIMESERIES_VARS:
        b64 = _make_timeseries_b64(
            ds_ts, var, label,
            style=section_style,
            vmin=vmin.get(var),
            vmax=vmax.get(var),
        )
        if b64:
            panels.append({"title": label, "b64": b64})

    ctx: dict[str, Any] = {
        "ts_name": ts_name,
        "ts_description": ts_cfg.get("description", ""),
        "cruise": cruise,
        "n_casts": n_casts,
        "n_profiles": n_profiles,
        "time_range": f"{time_start_str} – {time_end_str}",
        "cast_list_str": _compact_cast_list(cast_nums),
        "panels": panels,
        "fig_location_b64": fig_location_b64,
    }

    env = Environment(autoescape=True)
    html = env.from_string(_TIMESERIES_TEMPLATE).render(**ctx)
    out_file.write_text(html, encoding="utf-8")
    ds_all.close()
    return out_file
