"""Tier-2: generate the time-series HTML report page (all casts vs time)."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

import numpy as np
import xarray as xr
from jinja2 import Environment

from ctd_report._plots import _make_timeseries_b64

_TS_VARS: list[tuple[str, str]] = [
    ("temperature_1", "Temperature (°C)"),
    ("salinity_1", "Salinity (PSU)"),
    ("oxygen_1", "O₂ saturation (%)"),
]

_TIMESERIES_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Time series — {{ cruise }}</title>
<style>
  :root { --ocean: #1a3a5c; --seafoam: #e8f4f8; --accent: #2e86ab; --text: #1a1a2e; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #f5f7fa; color: var(--text); }
  header { background: var(--ocean); color: #fff; padding: 1rem 1.5rem; }
  header h1 { font-size: 1.3rem; }
  header .meta { font-size: 0.85rem; opacity: 0.8; margin-top: 0.25rem; }
  nav { background: var(--seafoam); padding: 0.6rem 1.5rem; border-bottom: 1px solid #cdd8e3; }
  nav a { color: var(--ocean); text-decoration: none; font-size: 0.9rem; margin-right: 0.5rem; }
  nav a:hover { text-decoration: underline; }
  nav span { color: #888; font-size: 0.9rem; margin-right: 0.5rem; }
  .card {
    background: #fff; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    padding: 1.25rem; margin: 1rem 1.5rem;
  }
  .card h2 { font-size: 1rem; color: var(--ocean); margin-bottom: 0.75rem; }
  .plot-wide img { max-width: 100%; height: auto; border-radius: 4px; }
  footer { text-align: center; padding: 1rem; font-size: 0.75rem; color: #999; }
</style>
</head>
<body>

<header>
  <div>
    <h1>Time series — all downcasts</h1>
    <div class="meta">{{ cruise }} &nbsp;·&nbsp; {{ n_casts }} downcasts &nbsp;·&nbsp; {{ date_range }}</div>
  </div>
</header>

<nav>
  <a href="index.html">Index</a> <span>›</span>
  <span>Time series</span>
</nav>

{% for panel in panels %}
{% if panel.b64 %}
<div class="card">
  <h2>{{ panel.title }}</h2>
  <div class="plot-wide">
    <img src="data:image/png;base64,{{ panel.b64 }}" alt="{{ panel.title }}">
  </div>
</div>
{% endif %}
{% endfor %}

<footer>Generated by ctd_report &nbsp;·&nbsp; {{ cruise }}</footer>
</body>
</html>"""


def generate_timeseries_page(
    profiles_path: Path,
    out_dir: Path,
    force: bool = False,
) -> Optional[Path]:
    """Generate the time-series HTML page from all downcast profiles.

    Parameters
    ----------
    profiles_path:
        Path to ``profiles.nc``.
    out_dir:
        Root output directory.
    force:
        Overwrite existing file if True.

    Returns
    -------
    Path to the written HTML file, or None on failure.
    """
    out_file = out_dir / "timeseries.html"
    if out_file.exists() and not force:
        return out_file
    out_dir.mkdir(parents=True, exist_ok=True)

    if not profiles_path.exists():
        return None

    try:
        ds = xr.open_dataset(profiles_path, decode_timedelta=False).load()
    except Exception:  # noqa: BLE001
        return None

    cruise = ds.attrs.get("cruise", "odb2026")

    is_down = ds["cast_type"].values == "down"
    n_casts = int(is_down.sum())

    t = ds["time_start"].values[is_down]
    t_sorted = sorted(str(x)[:10] for x in t if str(x) != "NaT")
    date_range = f"{t_sorted[0]} – {t_sorted[-1]}" if len(t_sorted) >= 2 else "—"

    panels = []
    for var, label in _TS_VARS:
        b64 = _make_timeseries_b64(ds, var, label, title=f"All casts — {label}")
        panels.append({"title": label, "b64": b64})

    ctx: dict[str, Any] = {
        "cruise": cruise,
        "n_casts": n_casts,
        "date_range": date_range,
        "panels": panels,
    }

    env = Environment(autoescape=True)
    html = env.from_string(_TIMESERIES_TEMPLATE).render(**ctx)
    out_file.write_text(html, encoding="utf-8")
    ds.close()
    return out_file
