"""Tier-2: per-group timeseries HTML report pages.

A timeseries in this codebase is a named group of repeat casts at one location
(yoyo CTDs, e.g. 24 h of repeated profiles).  Config is analogous to sections:
a name, a description, and a list of cast numbers.

The cruise-wide stacked overview plots (all casts, station-number x-axis) live on
index.html, generated by _index.py.  They are not timeseries pages.

Phase 2 work: generate_timeseries_page is a stub.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional


def generate_timeseries_page(
    ts_name: str,  # noqa: ARG001
    ts_cfg: dict,  # noqa: ARG001
    profiles_path: Path,  # noqa: ARG001
    out_dir: Path,  # noqa: ARG001
    force: bool = False,  # noqa: ARG001
    section_style: str = "pcolormesh",  # noqa: ARG001
) -> Optional[Path]:
    """Generate a per-timeseries HTML page for a named group of repeat casts.

    Like ``generate_section_page`` but for yoyo/repeat-station time series.
    Both downcasts and upcasts are plotted; x-axis is time or cast number.
    Output: ``<out_dir>/timeseries/<ts_name>.html``.

    Not yet implemented — Phase 2 work.
    """
    raise NotImplementedError("generate_timeseries_page is Phase 2 work")
