"""Tier-2: per-group timeseries HTML report pages.

A timeseries in this codebase is a named group of repeat casts at one location
(yoyo CTDs, e.g. 24 h of repeated profiles).  Config is analogous to sections:
a name, a description, and a list of cast numbers.

The cruise-wide stacked overview plots (all casts, station-number x-axis) live on
index.html, generated by _index.py.  They are not timeseries pages.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
import xarray as xr
from jinja2 import Environment

from ctd_report import _templates as _tmpl
from ctd_report._version import __version__ as _VERSION
from ctd_report.analysis import _add_aou, _add_teos10_profiles, _compact_cast_list
from ctd_report.plots import (
    _make_ladcp_section_b64,
    _make_station_map_b64,
    _make_timeseries_b64,
)
from ctd_report.section import _expand_cast_numbers

# ---------------------------------------------------------------------------
# Variables to plot (in order)
# ---------------------------------------------------------------------------

_TIMESERIES_VARS: list[tuple[str, str, str]] = [
    ("CT", "Conservative Temperature (°C)", "CT"),
    ("SA", "Absolute Salinity (g kg⁻¹)", "SA"),
    ("oxygen_1", "O₂ saturation (%)", "O₂"),
    ("AOU", "O₂ deficit (% sat)", "AOU"),
    ("fluorescence", "Fluorescence (mg m⁻³)", "Fluor"),
    ("turbidity", "Turbidity (NTU)", "Turb"),
]

# ---------------------------------------------------------------------------
# HTML template
# ---------------------------------------------------------------------------

_TIMESERIES_TEMPLATE = (
    """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ ts_name }} timeseries — {{ cruise }}</title>
<style>
  :root { --ocean: #1a3a5c; --seafoam: #e8f4f8; --accent: #2e86ab; --text: #1a1a2e; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #f5f7fa; color: var(--text); }
  header { background: var(--ocean); color: #fff; padding: 1rem 1.5rem; }
  header h1 { font-size: 1.3rem; }
  header .meta { font-size: 0.85rem; opacity: 0.8; margin-top: 0.25rem; }
  nav { background: var(--seafoam); padding: 0.5rem 1.5rem; border-bottom: 1px solid #cdd8e3;
        display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 0.4rem; }
  nav .breadcrumb a { color: var(--ocean); text-decoration: none; font-size: 0.9rem; margin-right: 0.3rem; }
  nav .breadcrumb a:hover { text-decoration: underline; }
  nav .breadcrumb span { color: #888; font-size: 0.9rem; margin-right: 0.3rem; }
  nav .quicklinks { display: flex; gap: 0.4rem; flex-wrap: wrap; }
  nav .quicklinks a { color: var(--ocean); text-decoration: none; font-size: 0.78rem;
                      background: #fff; border: 1px solid #b0c8dc; padding: 0.15rem 0.6rem;
                      border-radius: 999px; }
  nav .quicklinks a:hover { background: var(--ocean); color: #fff; }
  .legend { font-size: 0.82rem; color: #555; }
  .legend span { display: inline-block; width: 0.8rem; text-align: center; margin-right: 0.15rem; }
  .card {
    background: #fff; border-radius: 8px; box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    padding: 1.25rem; margin: 1rem 1.5rem;
  }
  .card h2 { font-size: 1rem; color: var(--ocean); margin-bottom: 0.75rem; }
  .meta-grid {
    display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
    gap: 0.5rem; font-size: 0.9rem;
  }
  .meta-item { display: flex; flex-direction: column; }
  .meta-item .label { font-size: 0.75rem; color: #888; }
  .meta-item .value { font-weight: 600; }
  .plot-wide { margin-top: 0.5rem; }
  .plot-wide img { max-width: 100%; height: auto; border-radius: 4px; }
  footer { text-align: center; padding: 1rem; font-size: 0.75rem; color: #999; }
</style>
</head>
<body>
<div id="top"></div>

<header>
  <h1>{{ ts_name }} — {{ cruise }}</h1>
  <div class="meta">{{ ts_description }} &nbsp;·&nbsp; {{ n_casts }} casts &nbsp;·&nbsp; casts {{ cast_list_str }} &nbsp;·&nbsp; {{ time_range }}</div>
</header>

<nav>
  <div class="breadcrumb">
    <a href="../index.html">Index</a> <span>›</span>
    <a href="../timeseries.html">Timeseries</a> <span>›</span>
    <span>{{ ts_name }}</span>
  </div>
  <div class="quicklinks">
    <a href="#s-meta">Metadata</a>
    {% if fig_location_b64 %}<a href="#s-map">Map</a>{% endif %}
    {% for panel in panels %}
    <a href="#s-panel-{{ loop.index }}">{{ panel.short }}</a>
    {% endfor %}
    {% if fig_ladcp_ts_b64 %}<a href="#s-ladcp">LADCP</a>{% endif %}
    <a href="#top">↑ Top</a>
  </div>
</nav>

<div class="card" id="s-meta">
  <h2>Timeseries metadata</h2>
  <div class="meta-grid">
    <div class="meta-item"><span class="label">Group</span><span class="value">{{ ts_name }}</span></div>
    <div class="meta-item"><span class="label">Description</span><span class="value">{{ ts_description }}</span></div>
    <div class="meta-item"><span class="label">Casts</span><span class="value">{{ cast_list_str }}</span></div>
    <div class="meta-item"><span class="label">Time range</span><span class="value">{{ time_range }}</span></div>
  </div>
  <div style="margin-top:0.75rem; display:flex; gap:0.5rem; flex-wrap:wrap;">
    {% for cn in cast_nums %}
    <a style="display:inline-block; background:#4a6fa5; color:#fff; padding:0.2rem 0.6rem;
       border-radius:999px; font-size:0.78rem; text-decoration:none;"
       href="../stations/cast_{{ cn }}.html">{{ cn }}</a>
    {% endfor %}
  </div>
</div>

{% if fig_location_b64 %}
<div class="card" id="s-map">
  <h2>Station location</h2>
  <img src="data:image/png;base64,{{ fig_location_b64 }}" alt="Yoyo location map" style="max-height:260px;width:auto;border-radius:4px;">
</div>
{% endif %}

{% for panel in panels %}
{% if panel.b64 %}
<div class="card" id="s-panel-{{ loop.index }}">
  <h2>{{ panel.title }}</h2>
  <div class="plot-wide">
    <img src="data:image/png;base64,{{ panel.b64 }}" alt="{{ panel.title }}">
  </div>
</div>
{% endif %}
{% endfor %}

{% if not panels %}
<div class="card"><p style="color:#888">No data available for these casts.</p></div>
{% endif %}

{% if fig_ladcp_ts_b64 %}
<div class="card" id="s-ladcp">
  <h2>LADCP velocity (U east, V north)</h2>
  <div class="plot-wide">
    <img src="data:image/png;base64,{{ fig_ladcp_ts_b64 }}" alt="LADCP U and V timeseries">
  </div>
</div>
{% endif %}

"""
    + _tmpl.FOOTER_TAIL
)


# ---------------------------------------------------------------------------
# Public function
# ---------------------------------------------------------------------------


def generate_timeseries_page(
    ts_name: str,
    ts_cfg: dict,
    profiles_path: Path,
    out_dir: Path,
    force: bool = False,
    section_style: str = "pcolormesh",
    vmin_override: dict[str, float] | None = None,
    vmax_override: dict[str, float] | None = None,
    all_meta: list[dict] | None = None,
    ladcp_dir: Path | None = None,
) -> Path | None:
    """Generate a per-timeseries HTML page for a named group of repeat casts.

    Plots both downcast and upcast profiles sorted by time_start on a shared
    time x-axis.  Output: ``<out_dir>/timeseries/timeseries_<ts_name>.html``.

    Parameters
    ----------
    ts_name:
        Group name (used in filename and page title).
    ts_cfg:
        Dict with ``cast_numbers``, ``description``, and ``color`` keys.
    profiles_path:
        Path to ``profiles.nc``.
    out_dir:
        Root output directory.
    force:
        Overwrite existing file if True.
    section_style:
        ``"pcolormesh"`` or ``"contourf"``.
    vmin_override, vmax_override:
        Per-variable colormap limit overrides.
    all_meta:
        List of per-cast metadata dicts (keys ``lat``, ``lon``, ``cast_num``);
        used to render a cruise-context location map.  If None, no map is shown.
    ladcp_dir:
        Directory containing processed LADCP ``.mat`` files named ``NNN.mat``.
        If None, the LADCP velocity panel is omitted.

    Returns
    -------
    Path to the written HTML file, or None if skipped or failed.
    """
    out_file = out_dir / "timeseries" / f"timeseries_{ts_name}.html"
    if out_file.exists() and not force:
        return out_file
    out_file.parent.mkdir(parents=True, exist_ok=True)

    cast_nums = _expand_cast_numbers(ts_cfg.get("cast_numbers", []))
    if not cast_nums:
        return None

    if not profiles_path.exists():
        return None

    try:
        ds_all = xr.open_dataset(
            profiles_path, decode_timedelta=False, engine="netcdf4"
        ).load()
    except Exception:  # noqa: BLE001
        return None

    all_cast_nums = ds_all["cast_number"].values
    mask = np.isin(all_cast_nums, cast_nums)
    if not mask.any():
        ds_all.close()
        return None

    ds_ts = ds_all.isel(N_PROF=mask)
    ds_ts = _add_teos10_profiles(ds_ts)
    ds_ts = _add_aou(ds_ts)

    # Sort all profiles (both down and up) by time_start
    order = np.argsort(ds_ts["time_start"].values)
    ds_ts = ds_ts.isel(N_PROF=order)

    cruise: str = ds_all.attrs.get("cruise", "odb2026")
    n_profiles = int(mask.sum())
    n_casts = len(cast_nums)

    times = ds_ts["time_start"].values
    time_start_str = str(times[0])[:16].replace("T", " ")
    time_end_str = str(times[-1])[:16].replace("T", " ")

    # Location map: centroid of the yoyo station highlighted against all cruise casts
    yoyo_lats = ds_ts["latitude"].values if "latitude" in ds_ts else np.array([])
    yoyo_lons = ds_ts["longitude"].values if "longitude" in ds_ts else np.array([])
    yoyo_lat = float(np.nanmedian(yoyo_lats)) if len(yoyo_lats) else float("nan")
    yoyo_lon = float(np.nanmedian(yoyo_lons)) if len(yoyo_lons) else float("nan")
    fig_location_b64: str | None = None
    if all_meta and np.isfinite(yoyo_lat) and np.isfinite(yoyo_lon):
        fig_location_b64 = _make_station_map_b64(yoyo_lat, yoyo_lon, all_meta)

    vmin = vmin_override or {}
    vmax = vmax_override or {}
    panels: list[dict[str, Any]] = []
    for var, label, short in _TIMESERIES_VARS:
        b64 = _make_timeseries_b64(
            ds_ts,
            var,
            label,
            style=section_style,
            vmin=vmin.get(var),
            vmax=vmax.get(var),
        )
        if b64:
            panels.append({"title": label, "short": short, "b64": b64})

    # LADCP: use downcast profiles only, x-axis = hours since first cast
    fig_ladcp_ts_b64: str | None = None
    if ladcp_dir is not None:
        if "cast_type" in ds_ts:
            ds_down = ds_ts.isel(N_PROF=ds_ts["cast_type"].values == "down")
        else:
            ds_down = ds_ts
        ladcp_cast_nums = [int(c) for c in ds_down["cast_number"].values]
        ladcp_lats = ds_down["latitude"].values.tolist()
        ladcp_lons = ds_down["longitude"].values.tolist()
        t_ns = ds_down["time_start"].values.astype("datetime64[ns]").astype(float)
        t_hours = (t_ns - t_ns[0]) / 3.6e12 if len(t_ns) > 0 else np.zeros(0)
        _figw = float(np.clip(0.25 * len(ladcp_cast_nums), 8, 16))
        fig_ladcp_ts_b64 = _make_ladcp_section_b64(
            ladcp_cast_nums,
            t_hours,
            "Hours since start",
            ladcp_dir,
            lats=ladcp_lats,
            lons=ladcp_lons,
            figsize=(_figw, 8.0),
        )

    ctx: dict[str, Any] = {
        "ts_name": ts_name,
        "ts_description": ts_cfg.get("description", ""),
        "cruise": cruise,
        "n_casts": n_casts,
        "n_profiles": n_profiles,
        "time_range": f"{time_start_str} – {time_end_str}",
        "cast_list_str": _compact_cast_list(cast_nums),
        "cast_nums": [f"{n:03d}" for n in sorted(cast_nums)],
        "panels": panels,
        "fig_location_b64": fig_location_b64,
        "fig_ladcp_ts_b64": fig_ladcp_ts_b64,
        "version": _VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }

    env = Environment(autoescape=True)
    html = env.from_string(_TIMESERIES_TEMPLATE).render(**ctx)
    out_file.write_text(html, encoding="utf-8")
    ds_all.close()
    return out_file
